<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Change Info</name>
   <tag></tag>
   <elementGuidId>ecd560f3-7a51-4c8c-bffd-c34dbd45e665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabs_history > li:nth-of-type(5) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='tabs_history']/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Change Info&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f2f1f5b-52cf-4ca9-9747-a0194729aa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#changed-data</value>
      <webElementGuid>166ecc22-e2b0-4fe3-a540-91e6b49ac0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>fcf1f4ea-99aa-492f-8c95-50db2ab8adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change Info</value>
      <webElementGuid>69498fb6-01b6-4a46-a81b-1cc8353955b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs_history&quot;)/li[5]/a[1]</value>
      <webElementGuid>a310ab5b-46c8-4b1d-ba75-f93227e3ca0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabs_history']/li[5]/a</value>
      <webElementGuid>08320864-898b-45ba-81f2-7ca6dfc6fd81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Change Info')]</value>
      <webElementGuid>2443c5b8-578a-4e35-a30f-463e31496de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Files'])[1]/following::a[1]</value>
      <webElementGuid>7df50973-155c-40f8-8148-76c20d471435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Substitution'])[1]/following::a[2]</value>
      <webElementGuid>8038410b-fe6b-4cdb-8166-b2ffcc8a642d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Segment'])[1]/preceding::a[1]</value>
      <webElementGuid>e6c304ca-52aa-4931-a259-61a8551bb262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih salah satu..'])[1]/preceding::a[1]</value>
      <webElementGuid>f9ee7a1d-d7cc-4bd8-b5ff-7134f431d9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change Info']/parent::*</value>
      <webElementGuid>1ffdddc8-4461-47c0-a0ba-c0f9112bac4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#changed-data')]</value>
      <webElementGuid>acdc3513-68ea-4876-b5d5-52b8e5a67d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[5]/a</value>
      <webElementGuid>09eeff6c-81fb-40e1-9282-02f2b587db02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#changed-data' and (text() = 'Change Info' or . = 'Change Info')]</value>
      <webElementGuid>e5b71396-735d-464d-99c0-71908ab114b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
