<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Primary Data</name>
   <tag></tag>
   <elementGuidId>48a14830-9b7b-4438-99d8-4d5984d3c0aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabs_history > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='tabs_history']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Primary Data&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>339a7f0d-978e-4afc-bdfd-ffc4d4034f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#primary-data</value>
      <webElementGuid>56831fc3-0da3-4e5d-a4f9-419f83e3819c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f4c51ad5-7a07-4766-9590-38bb58dd6bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e3f04579-2f0a-4075-a39b-b65918f309c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Primary Data</value>
      <webElementGuid>fb19de8b-c1c9-476a-9ce3-754ef06b8195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs_history&quot;)/li[1]/a[1]</value>
      <webElementGuid>129a6521-4fec-4323-8955-1c94731fb63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabs_history']/li/a</value>
      <webElementGuid>86df621f-ec30-4b6c-8bb0-42633cbda637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Primary Data')]</value>
      <webElementGuid>771cd13b-6761-4cd1-8da7-66053310380c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part'])[2]/following::a[1]</value>
      <webElementGuid>bb06e6a9-e359-4c3a-a9e7-3bdfa0c61251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Config'])[1]/following::a[2]</value>
      <webElementGuid>da8c1d02-9bd3-466a-9050-ebbf32e1dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary Data Skow'])[1]/preceding::a[1]</value>
      <webElementGuid>9a333d1c-74e6-47ab-b8e7-a8a0c2a2de52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Substitution'])[1]/preceding::a[2]</value>
      <webElementGuid>a92370b5-8166-429b-9d9e-b84bb11cee69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Primary Data']/parent::*</value>
      <webElementGuid>f3e1c031-d393-47a5-8a0c-41ffada64eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#primary-data')]</value>
      <webElementGuid>aa594df4-ad3b-442e-9b6e-ed53f7d8c0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li/a</value>
      <webElementGuid>d4b140ce-61a1-4fc7-9cc8-fd9b2cfbb790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#primary-data' and (text() = 'Primary Data' or . = 'Primary Data')]</value>
      <webElementGuid>d455cc30-b1f8-4631-ab1f-f662d342c656</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
