<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Substitution</name>
   <tag></tag>
   <elementGuidId>0963151b-d1d3-4ef5-b43c-bd49b4b1fbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabs_history > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='tabs_history']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Substitution&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1976ec83-f164-4b4e-99f7-22d307639700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#substitution-data</value>
      <webElementGuid>a22574ff-4459-47aa-8eb3-a36f0fd4ee66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d0e5edc1-b569-48df-a27a-5f1f9a7da28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Substitution</value>
      <webElementGuid>6d2000d4-a627-468e-8e7f-68f84a7157dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs_history&quot;)/li[3]/a[1]</value>
      <webElementGuid>02fdfc3c-e269-46e2-9beb-01ebf7b83990</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabs_history']/li[3]/a</value>
      <webElementGuid>b38a9c52-5ffb-401c-86f9-c5d2a302a320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Substitution')]</value>
      <webElementGuid>a3859df6-67b9-45cf-afb9-8d37cbf455de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary Data Skow'])[1]/following::a[1]</value>
      <webElementGuid>0cde37bf-338b-4d90-b6c6-f5ae6af21af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Data'])[1]/following::a[2]</value>
      <webElementGuid>6b17ab62-8e4b-40dd-b9ab-10e06c80ac0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Files'])[1]/preceding::a[1]</value>
      <webElementGuid>4cb2da25-b7af-410b-a4bf-83f7921016dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Info'])[1]/preceding::a[2]</value>
      <webElementGuid>6ddbccf7-31df-47e0-b546-a74bdef7f60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Substitution']/parent::*</value>
      <webElementGuid>e8f23b33-b2c6-4675-b208-80e838983234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#substitution-data')]</value>
      <webElementGuid>fa84d0c0-9085-4d43-95a1-8d6f65e49678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[3]/a</value>
      <webElementGuid>55353ec7-9394-4a7e-ab44-63ef30adef84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#substitution-data' and (text() = 'Substitution' or . = 'Substitution')]</value>
      <webElementGuid>cb7c6a9e-a25d-448f-bb19-65647f102ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
