<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Applied Year_tahun</name>
   <tag></tag>
   <elementGuidId>c9a7e9de-2f1f-480b-9c8b-cef0ba44e35d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tahun</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tahun']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tahun</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41c54016-e1c5-4783-9795-733d5d9edf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tahun</value>
      <webElementGuid>201a7e5b-ddde-494a-a1c6-b1f13a1a2f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tahun</value>
      <webElementGuid>7ec53586-a06c-4f7a-9ce7-58d26cceac6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm hasDatepicker</value>
      <webElementGuid>28df09a5-18a4-4a6d-a519-d47094d05801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8be4c0cd-56c1-4727-9cd6-8b0464af82c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tahun&quot;)</value>
      <webElementGuid>55ef60d4-db1d-418a-9640-7e9e46e94a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tahun']</value>
      <webElementGuid>6865cb33-772e-4bf7-b79c-1d378b4dc888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[11]/td[2]/input</value>
      <webElementGuid>84c47667-f289-41a2-9b6f-6d7eec733acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/input</value>
      <webElementGuid>4568a29c-1f1b-4469-a776-0c39fc4d7914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tahun' and @name = 'tahun' and @type = 'text']</value>
      <webElementGuid>6470d023-628c-4dd4-995f-d5b492fc5a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
