<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H_dim_h</name>
   <tag></tag>
   <elementGuidId>d073d8d9-a805-4eca-9854-4dd5c87a1c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim_h</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim_h']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dim_h</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>943f5a14-e2b3-43e0-ba9e-e8e4f12cd59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim_h</value>
      <webElementGuid>af6d2f17-4782-410b-8f0a-8e382513b81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dim_h</value>
      <webElementGuid>fb1180f9-0a55-444b-a93a-531fe685991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>3377e403-574d-4068-b2b2-9eee1d7449ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e2de69d-01c0-410a-a9ac-adf3a227a899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim_h&quot;)</value>
      <webElementGuid>38ffc642-b1c6-473c-9924-ffc89899d257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim_h']</value>
      <webElementGuid>abf51cc0-526e-45f6-8133-c4f25e0b5048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[5]/td[2]/table/tbody/tr/td[6]/input</value>
      <webElementGuid>7664b936-99b8-4014-aa89-ff8d17e7b7b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>b45354d6-e399-4d3b-a006-9ef9c6a50d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dim_h' and @name = 'dim_h' and @type = 'text']</value>
      <webElementGuid>680316ab-a4a3-4720-9828-08f8757323ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
