<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Catalog Part Name_model_name</name>
   <tag></tag>
   <elementGuidId>837dcb3c-fbe4-4745-bec3-673595e0bda6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#model_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='model_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill in part description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5340e114-d7c6-42a8-9e3b-016c0bb7f835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>model_name</value>
      <webElementGuid>9273a38d-334b-4c49-b1a3-074594ec4190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>model_name</value>
      <webElementGuid>77f32fc7-ff73-45dd-b8a8-dce58280d525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>06e9b362-5e21-480c-b5bd-39809b6a48e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d83dd299-dd61-40da-8e4c-0125852ae18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill in part description</value>
      <webElementGuid>2282528d-e5ae-46d2-9206-515ab1b01a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model_name&quot;)</value>
      <webElementGuid>d9063932-7c8d-491a-bae6-e23a2cc22ada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='model_name']</value>
      <webElementGuid>8ad63609-ec51-417e-970c-b50300af8f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[8]/td[2]/input</value>
      <webElementGuid>444fd2b9-4580-44c7-a808-b55159de99b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>4b9e7307-5a3b-4426-a10e-fb1e895b2070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'model_name' and @name = 'model_name' and @type = 'text' and @placeholder = 'Fill in part description']</value>
      <webElementGuid>2c43ea31-e10b-4a00-b2dd-afd508ee8300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
