<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Select a functional classification --</name>
   <tag></tag>
   <elementGuidId>889b2335-cad8-4336-b0df-14e5de9344ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-func_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-func_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;-- Select a functional classification --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b952efb-1b14-47c1-a1a1-a6a151d00783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e1c4626a-31a8-4bb8-a914-fe0088949b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-func_id-container</value>
      <webElementGuid>c743cb4f-5ad5-4f13-8ce5-6b1db472235e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Select a functional classification --</value>
      <webElementGuid>c919bb8d-6f98-4bf8-bbf1-275be84ebf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select a functional classification --</value>
      <webElementGuid>3f8dbe52-7c50-42ce-b951-284d3ba586f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-func_id-container&quot;)</value>
      <webElementGuid>e410d9d7-5737-4125-93bd-5e474eee05e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-func_id-container']</value>
      <webElementGuid>7bb6e266-752a-41b1-9864-8e01a7884c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[6]/td[2]/span/span/span/span</value>
      <webElementGuid>34eadcb6-6fa5-40e9-82ef-deb0272e197e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Classification'])[1]/following::span[4]</value>
      <webElementGuid>8dfcd198-c075-4178-b24b-64c775d7f933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accesories R'])[2]/following::span[6]</value>
      <webElementGuid>8c9b2329-638d-4442-b99a-78e02d487e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Category'])[2]/preceding::span[3]</value>
      <webElementGuid>21985134-7559-4b60-8ab7-747c7594a6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select a part category --'])[2]/preceding::span[3]</value>
      <webElementGuid>deb42c01-281a-4f08-8dca-78b7c8dbd3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/span/span/span/span</value>
      <webElementGuid>0ebf7343-dc80-45e9-8f0d-ed657987f763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-func_id-container' and @title = '-- Select a functional classification --' and (text() = '-- Select a functional classification --' or . = '-- Select a functional classification --')]</value>
      <webElementGuid>8ef096ba-5e07-44d9-832f-e46114c89b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih salah satu..'])[6]/following::span[4]</value>
      <webElementGuid>14e44a11-7275-4b89-b26a-47cae3055419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
