<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Select a lot num --</name>
   <tag></tag>
   <elementGuidId>8188d10c-3711-4288-ae76-e0287e2debc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-lot_number-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-lot_number-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;×-- Select a lot num --&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3174b2b7-b4a8-4edf-b200-1e5a41d57c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2382dbff-a167-46fc-a4ae-fad7dd0ef158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-lot_number-container</value>
      <webElementGuid>bc4ca95b-275e-4852-8814-c882ac278d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Select a lot num --</value>
      <webElementGuid>56afac67-5183-479d-ab7b-735fb33a4dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×-- Select a lot num --</value>
      <webElementGuid>c309ca09-e045-49d9-a111-d16a8c2c1f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-lot_number-container&quot;)</value>
      <webElementGuid>db05ea6a-168a-4e83-9f13-beb5bd618924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-lot_number-container']</value>
      <webElementGuid>2339416e-590d-4877-b9d1-5b1048be2510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[10]/td[2]/span/span/span/span</value>
      <webElementGuid>8d8bd414-4340-4407-8ada-1ffe42a46d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applied Month'])[1]/following::span[4]</value>
      <webElementGuid>4e9d7d6b-ab79-4aeb-b0eb-a66c8926c80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sequence Number'])[1]/following::span[4]</value>
      <webElementGuid>23c63005-6318-4130-b63a-64058b33ef48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applied Year'])[1]/preceding::span[4]</value>
      <webElementGuid>0c3bb161-cdf3-4404-a770-9736ccb750ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/span/span/span/span</value>
      <webElementGuid>40654af8-2a8a-4f7f-a3b6-2daf2f9e7163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-lot_number-container' and @title = '-- Select a lot num --' and (text() = '×-- Select a lot num --' or . = '×-- Select a lot num --')]</value>
      <webElementGuid>6241a0d9-8717-4245-94ff-bc41f279bb03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih salah satu..'])[8]/following::span[4]</value>
      <webElementGuid>7f2d666c-4fe2-4a53-bb67-1048832649ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
