<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CBZ-AD-DOR-0002-0118</name>
   <tag></tag>
   <elementGuidId>81d601e9-3cfe-4c23-9784-89b568632693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.odd > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-part-list']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=gridcell[name=&quot;CBZ-AD-DOR-0002-0118&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4b95ecbc-b77c-46ba-b64b-2de7fd349fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CBZ-AD-DOR-0002-0118</value>
      <webElementGuid>06d4aecf-243f-4674-9a34-99c924dfed42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-part-list&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]</value>
      <webElementGuid>541f79c8-b3f0-46da-9267-1f9f1f1ded0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-part-list']/tbody/tr/td[2]</value>
      <webElementGuid>a83989b3-467f-462a-8e52-eb7848c64474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[3]/following::td[2]</value>
      <webElementGuid>8524a61e-6dae-4da0-816e-09114a7f4418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/following::td[2]</value>
      <webElementGuid>d419a686-d8ef-4158-9cee-7888e25aa885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBZ-AD-DOR-0002-0118'])[2]/preceding::td[1]</value>
      <webElementGuid>14c1a5e9-3d23-4835-a2df-658cc229e3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOOR'])[1]/preceding::td[2]</value>
      <webElementGuid>bf8b2556-7c96-4f14-b54c-dc9ee1296825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CBZ-AD-DOR-0002-0118']/parent::*</value>
      <webElementGuid>140a9c1e-d9c1-456d-9809-ef27e7bd6d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>7e424823-0575-493b-a357-c4ae72f2532d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CBZ-AD-DOR-0002-0118' or . = 'CBZ-AD-DOR-0002-0118')]</value>
      <webElementGuid>2cb536a9-7e2c-4625-9696-784b4a28fba5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
