<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Specification_spec</name>
   <tag></tag>
   <elementGuidId>cf47da4d-d909-4a99-a06f-27a8466cbcaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='spec']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Fill in specification (max 250 char)..&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4df67d93-76d2-4dfc-9791-b3995c8540b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spec</value>
      <webElementGuid>c52b92c3-811f-429a-83c9-e56ae1e6f89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spec</value>
      <webElementGuid>22a4cdb1-ddfe-42a5-b16c-fd2388b7ad51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-xxl</value>
      <webElementGuid>22c044c3-d0fa-498f-9dfe-b8c4fc59a160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Fill in specification (max 250 char)..</value>
      <webElementGuid>584d4522-ef11-4ed8-8273-cb32d9a3f206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spec&quot;)</value>
      <webElementGuid>f6a6fffd-77ed-47e5-a944-91bb01d0e34c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='spec']</value>
      <webElementGuid>8883e7ea-7c58-42ea-b25e-072b2b9feee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[9]/td[2]/textarea</value>
      <webElementGuid>f74a0701-6095-4f64-adb0-2ae9ec6107ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/textarea</value>
      <webElementGuid>2f28d8c7-885e-4e72-b711-562a8025d213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'spec' and @id = 'spec' and @placeholder = 'Fill in specification (max 250 char)..']</value>
      <webElementGuid>71dacd09-f1c1-4a5d-8a03-583b6ccbe290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
