<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_fullname</name>
   <tag></tag>
   <elementGuidId>bd768c9b-1fe5-4532-a324-278c79554db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.text-left > input[name=&quot;fullname&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='fullname'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ketik Nama &quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89cf0cea-c788-496c-b4ff-f091ddc6cb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5266397c-0a4c-4d9e-8db5-f1c00531cb06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fullname</value>
      <webElementGuid>cf178be1-ad67-45c8-9964-113d048fd7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-calculator</value>
      <webElementGuid>6cb3e62c-aa4d-4593-a361-d1c72e874f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik Nama </value>
      <webElementGuid>b6e3bcaf-0212-4405-a1ff-73e35d96f0de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculator-form&quot;)/section[@class=&quot;section-3 active-section&quot;]/div[@class=&quot;wrap-form-calculator&quot;]/div[@class=&quot;row d-flex justify-content-center  mt-5&quot;]/div[@class=&quot;col-md-6 text-left&quot;]/input[@class=&quot;input-calculator&quot;]</value>
      <webElementGuid>5f098edd-c5a9-44c2-8d40-7e9c2beae937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='fullname'])[2]</value>
      <webElementGuid>122e51fb-428a-49ba-a6aa-bee83d7b6404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calculator-form']/section[3]/div[2]/div[2]/div/input</value>
      <webElementGuid>160c9a96-49ad-47c9-a57a-2e1423461c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>d47f824f-291f-47dd-b8ab-b2cb5ed81e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fullname' and @placeholder = 'Ketik Nama ']</value>
      <webElementGuid>29ee6f8e-bb17-4753-80fa-8903d1e775c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
