<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__promo_name</name>
   <tag></tag>
   <elementGuidId>abe84e48-cb11-4053-9834-15652213dcf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promo_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promo_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88945db2-99f0-477e-a55b-a6d550a9ea89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>608ed566-235b-47d2-9741-57ae4231c084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promo_name</value>
      <webElementGuid>fd74b2e1-a1ca-4fec-a4fb-72845ca093a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promo_name</value>
      <webElementGuid>a41255a0-e9b4-4829-ab71-1f118f13df29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Promo Discount 70%</value>
      <webElementGuid>4e01691e-eb92-4caf-a756-d0c9938250d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promo_name&quot;)</value>
      <webElementGuid>78b4296f-b43b-4404-a3ce-5e9e373ae74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promo_name']</value>
      <webElementGuid>e8f8f11f-d7e0-4c3c-bf53-c72dfa60ef2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div[3]/div/div[3]/div/form/div/div/div/input</value>
      <webElementGuid>878504cd-1576-4678-9504-f3a2a83d2726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>83a3d63d-b075-4dfd-92f0-c1a4f7d80b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'promo_name' and @id = 'promo_name' and @placeholder = 'Promo Discount 70%']</value>
      <webElementGuid>7339fb68-f4d2-43a1-8963-3d7f653eba7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
