<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__campaign_prefix</name>
   <tag></tag>
   <elementGuidId>150bdd58-1e90-4e73-8479-dff3622b92a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/input&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#campaign_prefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>126578a0-3bb8-42f5-8244-0596b7d5171b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60a69e2b-7110-4450-9a53-301506d5ff28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>campaign_prefix</value>
      <webElementGuid>8430c66f-8905-4731-9a94-471dd97bae93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>campaign_prefix</value>
      <webElementGuid>ca0ab296-8280-47fc-8f7c-6628cd4741f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Prefix</value>
      <webElementGuid>7c9352e4-fbcc-407e-9240-f192a3448223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;campaign_prefix&quot;)</value>
      <webElementGuid>eee5e4e2-004a-49b1-87a4-9281fd1b57e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='campaign_prefix']</value>
      <webElementGuid>9baec9ac-f23b-47bb-b295-a3b7ca6ad88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/form/div[6]/div/div/input</value>
      <webElementGuid>f0d2fce1-d78e-4f7c-9899-9d4341ef6585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>4bc360d5-00ce-4f97-bed3-b7b01cc52683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'campaign_prefix' and @id = 'campaign_prefix' and @placeholder = 'Add Prefix']</value>
      <webElementGuid>fa262354-9788-47d2-bb14-148fa573ee5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
