<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master</name>
   <tag></tag>
   <elementGuidId>bd80049c-ffc9-420d-a301-21cfcd26f1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[10]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Master&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb6d363b-3e37-44d9-a529-a31d0ee71eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer</value>
      <webElementGuid>834a83d3-3072-4739-8b2c-ad1cd0bfc6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master</value>
      <webElementGuid>38297fb9-5511-46cc-bd52-a81cb4bb4c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;false&quot;]/div[@class=&quot;px-8 pb-2 w-full&quot;]/div[@class=&quot;flex h-12 justify-between&quot;]/div[@class=&quot;flex xl:gap-6 sm:gap-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative group pr-6 pt-5&quot;]/div[@class=&quot;xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer&quot;]</value>
      <webElementGuid>924c45c5-c3c6-47b0-96e2-20f325fc9eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[10]/div/div</value>
      <webElementGuid>867b6ea0-f251-4800-9b55-b6b949262575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resign Report'])[1]/following::div[3]</value>
      <webElementGuid>9478311d-a581-4c62-8219-d16c18b6177d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PMK Report'])[1]/following::div[4]</value>
      <webElementGuid>1e122c4e-460b-4bf1-88b0-9ca6e52a6ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MPP Period Setting'])[1]/preceding::div[2]</value>
      <webElementGuid>6c4d54f9-85a9-4be9-a720-0fbaa71ad150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alternate Approval Setting'])[1]/preceding::div[3]</value>
      <webElementGuid>ede630f0-2586-4a4e-8f04-c761755f3a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master']/parent::*</value>
      <webElementGuid>309d2f9c-7017-4de8-900f-4041b0a4633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div</value>
      <webElementGuid>5f100d55-ddf1-4148-b42d-d3c9d4689253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Master' or . = 'Master')]</value>
      <webElementGuid>fbe00724-8f54-41b9-b618-e98398eebfd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
