<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Became T</name>
   <tag></tag>
   <elementGuidId>209cd99d-a482-43be-94de-e85f9dc4fe05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kpi_definition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='kpi_definition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Definition of the Performance Dictionary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a26d4b81-a0ab-4fdb-9adc-7c8d547a39d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3c9ff981-08b7-4963-bd01-b0c3309f244c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kpi_definition</value>
      <webElementGuid>11b0cd01-5dbe-4f9b-85dc-40536d861274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kpi_definition</value>
      <webElementGuid>6d3baff2-f1e6-4362-8574-f8e72dd35565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a605e915-89b5-4d9d-b52f-40be2123b744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>0ed144cb-40f0-4146-8ee1-ac690a9789ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Definition of the Performance Dictionary</value>
      <webElementGuid>add15c77-cbf0-43b2-8e7b-7967996eb89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-lg border-0 px-2 py-3 text-gray-900 shadow-sm ring-1 ring-inset placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-pink-600 sm:text-md sm:leading-6 false resize-none</value>
      <webElementGuid>a77994f7-9ce4-499a-984d-269bb73c3591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Became T</value>
      <webElementGuid>abb17eff-5f5f-4159-8d1e-2cee3ae4ed12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kpi_definition&quot;)</value>
      <webElementGuid>59bab110-2388-4efd-929f-a6945aa9c9e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='kpi_definition']</value>
      <webElementGuid>60ed3c11-f412-4da6-9bf7-77e6d94cac0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div[3]/div/textarea</value>
      <webElementGuid>079e22a0-bad3-437f-bcd3-be044c807f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::textarea[1]</value>
      <webElementGuid>5e9f7ddd-66aa-416f-8bbf-c99f499e69b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::textarea[1]</value>
      <webElementGuid>fefa47f9-2cf2-4bfe-88c8-ecdde38cf224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Became T']/parent::*</value>
      <webElementGuid>3cd84d0b-08d7-4150-97fc-4cc0cc3538d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3e9f8a8a-4fd6-4024-b40a-3f807e9ad586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'textarea' and @name = 'kpi_definition' and @id = 'kpi_definition' and @placeholder = 'Definition of the Performance Dictionary' and (text() = 'Became T' or . = 'Became T')]</value>
      <webElementGuid>1a8e6e89-86a1-4dd4-acb2-d415908a0fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
