<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Performance</name>
   <tag></tag>
   <elementGuidId>e493c9d7-d352-49b5-ac70-a8fe1fd018a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[8]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Performance&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0ff2ea7-f2af-41bb-a211-44174302a1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer</value>
      <webElementGuid>8963ea84-4d25-483f-a8cd-e792578a4e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance</value>
      <webElementGuid>ac625b54-299b-4c9a-9a4f-dbbee7a6a09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;false&quot;]/div[@class=&quot;px-8 pb-2 w-full&quot;]/div[@class=&quot;flex h-12 justify-between&quot;]/div[@class=&quot;flex xl:gap-6 sm:gap-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative group pr-6 pt-5&quot;]/div[@class=&quot;xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer&quot;]</value>
      <webElementGuid>1a91f916-36dc-4c5e-a311-5d2dd0040bf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[8]/div[2]/div</value>
      <webElementGuid>87dc576b-756c-4a60-ba6e-0288b3e64b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resign Approval'])[1]/following::div[4]</value>
      <webElementGuid>fdb7c27b-ee89-42b2-851a-71fd6d3b2864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Resign'])[1]/following::div[5]</value>
      <webElementGuid>7cd0496f-0e47-493d-a068-1f57c633ae8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Performance Plan Approval'])[1]/preceding::div[2]</value>
      <webElementGuid>24c0d3c0-0b35-44cd-9830-c205d5d245a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Performance']/parent::*</value>
      <webElementGuid>045a34ed-7a5d-4eb6-a91b-7ffd2884a422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div</value>
      <webElementGuid>613e4e4c-b37f-480c-8a92-86f00bf99ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Performance' or . = 'Performance')]</value>
      <webElementGuid>a880b78f-ef19-4fb0-91fa-4c55a75ae4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
