<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear All_performance_year</name>
   <tag></tag>
   <elementGuidId>d586c939-bca4-4f98-bbdb-20ca8669b319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='performance_year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;performance_year&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Performance Year&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cfeae7c-e79e-4308-9637-2479cf4de769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6350e4ab-ab6e-4242-be97-5550c1d3aef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>performance_year</value>
      <webElementGuid>d9612690-7225-482b-9df2-12fd994d87ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>397b2a3f-18cc-4d90-a65e-abc1e008948b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-lg border-0 px-2 bg-neutral-800 text-white py-2 placeholder:text-white placeholder:font-thin placeholder:text-sm</value>
      <webElementGuid>edb7957d-8fd7-4111-bd2f-095fc02714e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Performance Year</value>
      <webElementGuid>2c858b56-a54a-4264-966d-920093f2a256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;mx-auto pt-4 px-8 grid grid-cols-5 gap-x-4 gap-y-2&quot;]/div[@class=&quot;mt-2&quot;]/input[@class=&quot;block w-full rounded-lg border-0 px-2 bg-neutral-800 text-white py-2 placeholder:text-white placeholder:font-thin placeholder:text-sm&quot;]</value>
      <webElementGuid>6e014689-6fdb-4ad8-a148-d23c35060e6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='performance_year']</value>
      <webElementGuid>e00e8cd8-39bb-4254-998d-554bc2ea0fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div[3]/div[2]/input</value>
      <webElementGuid>166ed284-648f-4709-b7f0-c8a59b951c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ff81c3ae-c76c-4232-8d7e-164766daaa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'performance_year' and @placeholder = 'Performance Year']</value>
      <webElementGuid>cb5688bd-e71a-4da6-bcdb-69c2c32e2bbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
