<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Ketik Lokasi Pembelian atau Nama Toko --</name>
   <tag></tag>
   <elementGuidId>f5207f37-cfb5-4fa2-8ce5-d59f09e79525</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-placebuy-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-placebuy-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;-- Ketik Lokasi Pembelian atau Nama Toko --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ecae6556-6914-4993-9396-ddd234ad89fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ec2843a2-f913-4ba0-bb65-4b8dc160b12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-placebuy-container</value>
      <webElementGuid>92c3b02d-0440-44e1-ae1d-9b158e15ac11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e2574360-106d-4603-b009-fe859bbe01b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a1457ed4-2a80-4744-ab18-60917515403e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Ketik Lokasi Pembelian atau Nama Toko --</value>
      <webElementGuid>dfc6b481-0449-4747-97b6-4f1f5e17d728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Ketik Lokasi Pembelian atau Nama Toko --</value>
      <webElementGuid>368b2a43-4f71-45ac-a11a-5f5b9a9f5b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-placebuy-container&quot;)</value>
      <webElementGuid>d2a01f73-2e61-493a-840e-c91cf735a0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-placebuy-container']</value>
      <webElementGuid>83154e41-041f-41b2-9d1c-1d1f2f844d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-ciao-claim-cashback']/div/div[2]/div/div/span/span/span/span</value>
      <webElementGuid>6afa3f53-5e37-4504-8d48-7e3bd123a821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tempat Pembelian'])[1]/following::span[4]</value>
      <webElementGuid>e4aeee2d-1e2d-4ef8-84d1-1707946a362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pembelian'])[1]/following::span[4]</value>
      <webElementGuid>8c7f0438-93a5-4210-b271-3a61223a6112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Pembelian'])[1]/preceding::span[5]</value>
      <webElementGuid>c76d1300-b53e-4f45-b8af-58d8865fa10a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>fe768453-ccef-4402-b261-84e9b9d60114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-placebuy-container' and @title = '-- Ketik Lokasi Pembelian atau Nama Toko --' and (text() = '-- Ketik Lokasi Pembelian atau Nama Toko --' or . = '-- Ketik Lokasi Pembelian atau Nama Toko --')]</value>
      <webElementGuid>b316add8-7604-48b5-ad53-ced0e0ebed96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
