<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>1d2a0954-5a49-4cd3-a2fd-8caeda07bd88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2' and @type = 'submit' and (text() = 'Delete' or . = 'Delete')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89a82e2c-48c4-4a26-a446-c7f3f38d1e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      <webElementGuid>744441f4-dc2b-4e59-aef6-58a98d3d13d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e016c291-bf38-43d3-bb83-dd39c8c792cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete-header subHeaderBtn dropdown-item</value>
      <webElementGuid>0b9cf8a9-43f0-4cdc-8508-3639d31ac716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>bf8d0d29-8d4d-45a7-b6f4-3a8c8da47483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2&quot;)</value>
      <webElementGuid>9ec47a5a-1ecb-4e49-bb2a-9770364fde8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      <webElementGuid>3cd962e3-e0b8-4ee0-a51e-f2e53137b766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul/li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>23d2147f-f379-4947-b105-3cd5fa0c30c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[28]/following::button[1]</value>
      <webElementGuid>a45a33bc-92af-4efe-bcd1-f2f514c0da33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[28]/following::button[1]</value>
      <webElementGuid>3e5cb44c-f446-4d24-8fed-407fb33a1dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporasi Nihonggo'])[2]/preceding::button[1]</value>
      <webElementGuid>70d65bee-4b4e-4373-882a-6cef1190da30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[29]/preceding::button[1]</value>
      <webElementGuid>8d21f7f0-2e0b-49d4-a1ea-b2296327d5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>877add47-3c08-4f4e-a997-df25ee7a2bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2' and @type = 'submit' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>d002b267-3232-4343-8bcc-c56f5a3db613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
