<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Product DimensionHeight (mm) Width (mm)_00446a</name>
   <tag></tag>
   <elementGuidId>ff5c86b3-4891-461b-8242-d1ca9428b256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form div >> internal:has-text=&quot;Product DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Volume (kgv) Thic&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ce186250-483c-4140-ba9a-63f232fbc0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-footer</value>
      <webElementGuid>b9ad3795-27e7-441b-9b2a-f33d3d238d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Product DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Volume (kgv) Thickness (mm) Weight Weight Unit Select Weight TypeGramKGPackage DimensionOuter Height (mm) Outer Width (mm) Outer Length (mm) Outer Depth (mm) Outer Weight (kg) Cut Out DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Topmount Cut Out DimensionHeight (mm) Width (mm) Length (mm) Undermount Cut Out DimensionHeight (mm) Width (mm) Length (mm) </value>
      <webElementGuid>46dc6344-2a93-4149-b10e-eade6cf517df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/form[@class=&quot;form-create-product&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card-footer&quot;]</value>
      <webElementGuid>2caa7591-57c7-474d-81ab-83f3881d54b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]</value>
      <webElementGuid>8ace2c5d-86bf-406b-becd-7a94f19defc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number'])[1]/following::div[3]</value>
      <webElementGuid>7a88d98c-fd7c-4ed2-86fe-c53eac5f9296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Launch Date'])[1]/following::div[5]</value>
      <webElementGuid>2c43b964-d34d-4b4b-b0a4-3c08c66f947a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>8a8058a5-6e0f-459f-87f8-36377254e2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Product DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Volume (kgv) Thickness (mm) Weight Weight Unit Select Weight TypeGramKGPackage DimensionOuter Height (mm) Outer Width (mm) Outer Length (mm) Outer Depth (mm) Outer Weight (kg) Cut Out DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Topmount Cut Out DimensionHeight (mm) Width (mm) Length (mm) Undermount Cut Out DimensionHeight (mm) Width (mm) Length (mm) ' or . = 'Product DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Volume (kgv) Thickness (mm) Weight Weight Unit Select Weight TypeGramKGPackage DimensionOuter Height (mm) Outer Width (mm) Outer Length (mm) Outer Depth (mm) Outer Weight (kg) Cut Out DimensionHeight (mm) Width (mm) Length (mm) Depth (mm) Topmount Cut Out DimensionHeight (mm) Width (mm) Length (mm) Undermount Cut Out DimensionHeight (mm) Width (mm) Length (mm) ')]</value>
      <webElementGuid>1fee59db-fcc1-428a-a4fb-165831a6194d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
