<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Model CodeItem NameGroupSelect GroupFG _f6dbed</name>
   <tag></tag>
   <elementGuidId>55b9448b-a714-4984-9789-4e71bc9661fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Model CodeItem NameGroupSelect GroupFG - HOME APPLIANCEFG - PROFESSIONALSupplier&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdb4bd7e-994d-4b76-acd6-4f4d2d9b6723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-3</value>
      <webElementGuid>c410fe0e-4313-4840-bcf8-bc73e6932af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Model CodeItem NameGroupSelect GroupFG - HOME APPLIANCEFG - PROFESSIONALSupplier CodeLaunch DateSerial Number</value>
      <webElementGuid>2dcf5c16-e350-48f3-9f1c-0787266705e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/form[@class=&quot;form-create-product&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]</value>
      <webElementGuid>babf0434-389e-4805-aaa6-016a11d581c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]</value>
      <webElementGuid>31b56289-66c0-469b-9031-2e7761297eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barcode EAN-13'])[1]/following::div[3]</value>
      <webElementGuid>f7738341-b0f8-4bb7-9802-eb7d97ed5d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scale'])[1]/following::div[4]</value>
      <webElementGuid>a18c7b16-c764-4b65-8fe8-dedb2231935a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]</value>
      <webElementGuid>4a9d4e08-03bc-4128-ab3f-6eae34fb4849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Model CodeItem NameGroupSelect GroupFG - HOME APPLIANCEFG - PROFESSIONALSupplier CodeLaunch DateSerial Number' or . = 'Model CodeItem NameGroupSelect GroupFG - HOME APPLIANCEFG - PROFESSIONALSupplier CodeLaunch DateSerial Number')]</value>
      <webElementGuid>37fb8f08-a169-4fb5-8d29-c29e1b2079a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
