<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier Code_cardcode</name>
   <tag></tag>
   <elementGuidId>776c7946-29a6-47da-8aac-f332fdbffe6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='search'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group > div > div.input-group > #search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type min: 4 char of supplier name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a508313-78d8-479d-acd3-71e530a6787e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e6b193e5-b62f-4e23-9e75-1c2b05ff0f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardcode</value>
      <webElementGuid>1bd47030-c3b3-4d42-b354-fc4356089aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type min: 4 char of supplier name</value>
      <webElementGuid>9dddf44d-2ef0-4ef3-b48e-3e8585f216a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control searchField</value>
      <webElementGuid>57f541c1-eb6d-495c-88d9-dffd0d797aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/form[@class=&quot;form-create-product&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3&quot;]/div[@class=&quot;form-group&quot;]/div[1]/div[@class=&quot;input-group&quot;]/input[@id=&quot;search&quot;]</value>
      <webElementGuid>892f97b6-a0ac-4165-a54e-1f1d44c9c3d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='search'])[2]</value>
      <webElementGuid>34f69676-516f-4298-82b1-e04b1123a16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]/div[4]/div/div/input</value>
      <webElementGuid>5aea1e6b-f41c-442b-958c-e38815a2dcfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/div/input</value>
      <webElementGuid>b66644a6-850c-4020-9337-e944d8aea895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @name = 'cardcode' and @placeholder = 'Type min: 4 char of supplier name']</value>
      <webElementGuid>4126e399-aab8-42ab-9f8e-d45892feb856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
