<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Width (mm)_cut_out_width_topmount</name>
   <tag></tag>
   <elementGuidId>9d2c40da-fda8-40f5-83c5-70b59750e467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_width_topmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_width_topmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Topmount Cut Out Width (mm)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d5f81d7-f0ab-43b7-9f22-0b8b023e5f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_width_topmount</value>
      <webElementGuid>0545a926-7db6-4292-b38e-25ca7573b667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_width_topmount</value>
      <webElementGuid>ed539f0c-4dd9-4e7a-b166-93c2fbbaae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56c34ad5-57da-4941-ae3f-390216c18999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Topmount Cut Out Width (mm)</value>
      <webElementGuid>86ced3b6-88ad-4561-9d09-06acc2f1c8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>23b16983-32c1-4905-9625-ea67b449330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_width_topmount&quot;)</value>
      <webElementGuid>fcaa0254-9a9f-41f9-9657-7e0d7aabca75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_width_topmount']</value>
      <webElementGuid>76b1f58e-74cb-4b54-b8da-2184208818c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[4]/div[2]/div[2]/input</value>
      <webElementGuid>85e264f1-f24e-4de7-86bb-70629b2fc534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/input</value>
      <webElementGuid>230af3a9-3829-465d-acdb-cf6f3b321a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_width_topmount' and @name = 'cut_out_width_topmount' and @type = 'text' and @placeholder = 'Topmount Cut Out Width (mm)']</value>
      <webElementGuid>b066a41b-c2f8-4f70-9e91-927896db9e1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
