<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select GroupFG - HOME APPLIANCEFG - _be317a</name>
   <tag></tag>
   <elementGuidId>e44b3ed4-5a3f-41e9-b97f-534bbefcb0cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='group_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#group_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#group_code</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>65f6a700-de4f-4a86-9323-dd4b76aed94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>group_code</value>
      <webElementGuid>09f0b060-10d7-421c-b8ba-0eccc53030da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>20328746-cc1b-4d74-bcc0-feb303a8fce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>group_code</value>
      <webElementGuid>05b6ae51-18a5-46ad-9936-c9a995a73772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL</value>
      <webElementGuid>08d3bca1-30c5-4386-9df9-f51993e0cef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group_code&quot;)</value>
      <webElementGuid>de102094-993e-4e39-87a5-6e07d1b9b97a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='group_code']</value>
      <webElementGuid>6fcfad43-cc6f-41b4-8877-af18495e3168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]/div[3]/select</value>
      <webElementGuid>6b3b57bf-dc43-4959-932b-c5b6fa7c916b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/following::select[1]</value>
      <webElementGuid>17ba6533-887e-4a6b-bc57-855af4826e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Name'])[1]/following::select[1]</value>
      <webElementGuid>c4ea9438-8d35-40c3-8714-f5126060fd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Code'])[1]/preceding::select[1]</value>
      <webElementGuid>23cb084c-fdca-4951-8c0e-b0fd81e509dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Launch Date'])[1]/preceding::select[1]</value>
      <webElementGuid>cca09dcf-5b17-434a-b739-a3dbb922a05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/select</value>
      <webElementGuid>beb59999-519b-41b2-9d6b-cc36f54c504f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'group_code' and @name = 'group_code' and (text() = 'Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL' or . = 'Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL')]</value>
      <webElementGuid>1170ae76-b837-43d5-a773-5f337ad82ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
