<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Show 3 Filters</name>
   <tag></tag>
   <elementGuidId>8ac70f5c-c304-4fcf-be83-7264f42c4ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show 3 Filters&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a255593-73c2-4a1e-8165-0a20e31012c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99bc22b1-7d41-417f-91dc-d8d997e5f3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow-sm hover:bg-zinc-800 disabled:opacity-60</value>
      <webElementGuid>6c05dd4b-70c9-4eab-aa8a-8ed26139bbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show 3 Filters</value>
      <webElementGuid>4f09b9da-e896-4208-b6f5-9b7c62bb3d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;h-16 mx-auto&quot;]/div[2]/div[@class=&quot;bg-white rounded-lg w-96 z-50 mt-2 px-4 py-3 drop-shadow-lg&quot;]/div[@class=&quot;flex justify-between pt-4&quot;]/button[@class=&quot;rounded bg-zinc-900 px-2 py-1 text-xs font-semibold text-white shadow-sm hover:bg-zinc-800 disabled:opacity-60&quot;]</value>
      <webElementGuid>aebee7b1-e87d-43d7-980a-33e54afb8999</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>f9672ce0-e267-4ac1-827b-77dc6ea52b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div[2]/div[2]/div/div[6]/button[2]</value>
      <webElementGuid>4f23dd96-406f-4bdb-b79a-a96cd377aedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear All'])[1]/following::button[1]</value>
      <webElementGuid>7e8e7226-86d0-4d5a-9223-80dcf45fa36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Number'])[1]/following::button[2]</value>
      <webElementGuid>10df3db0-cea7-45a8-9161-20a599290115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::button[1]</value>
      <webElementGuid>78614d64-b715-4468-92c4-2e29cfc2bc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance Number'])[2]/preceding::button[1]</value>
      <webElementGuid>e13be7be-2005-4645-a213-aaee78a52b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show']/parent::*</value>
      <webElementGuid>9bdf43e0-cb48-41a0-9756-cc159396cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>63981572-dca6-4ea8-a7f0-9d57c41014fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Show 3 Filters' or . = 'Show 3 Filters')]</value>
      <webElementGuid>73e255ac-e076-479a-8482-2e6ffd3b9498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
