<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mppPeriod</name>
   <tag></tag>
   <elementGuidId>902fdf17-8613-4d58-a12a-e3c4d4fd5fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Performance Year&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74079bbf-7c66-4afd-86a2-486dc6ba435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstFilter</value>
      <webElementGuid>c6f43179-06fb-4d55-99f8-d55f5fb24489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mppPeriod</value>
      <webElementGuid>e9d0f8c2-38e3-4e4e-be14-e639bfd5ff31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b5685005-d159-4e17-ae55-0737765e40f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-4 w-4 rounded border-gray-300 text-pink-500 focus:ring-pink-500</value>
      <webElementGuid>b37551b9-d8aa-4ac6-8da1-b1eabdca930d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstFilter&quot;)</value>
      <webElementGuid>67c3a998-dd89-4198-9915-811c38c9ad10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstFilter']</value>
      <webElementGuid>bb4d4647-f3be-4dfe-93fe-0cd650919fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div[2]/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>a3b40e5b-b0c3-4363-8f8b-9aaf13ca53e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0c2fa592-6cf9-44eb-b1e3-9b25e6456e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstFilter' and @name = 'mppPeriod' and @type = 'checkbox']</value>
      <webElementGuid>a960ac80-559b-409b-975b-cf4ac1944d79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
