<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add new sub menu</name>
   <tag></tag>
   <elementGuidId>879d905d-0c83-4eb4-bf31-8c3ff26773b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submenu-dbbe59b56374d0128514affe177198a6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submenu-dbbe59b56374d0128514affe177198a6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Add new sub menu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e230a3a5-7561-4920-89b7-8b36c7888800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submenu-dbbe59b56374d0128514affe177198a6</value>
      <webElementGuid>2415edaa-4b86-49c6-a1fa-26d0459eb6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unique-id</name>
      <type>Main</type>
      <value>dbbe59b56374d0128514affe177198a6</value>
      <webElementGuid>4c7ed7be-2969-401e-bf4a-2a4889c7dcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>#subMenuNavigation</value>
      <webElementGuid>27cb3735-2909-4438-a283-1b9b666d66a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>bc2322f6-7b70-4e50-81e0-71f84c0ada8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button--primary button--icon add-sub-menu mb-3 mt-3</value>
      <webElementGuid>b8dae0ff-70ff-4aae-be5f-f244e9653f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add new sub menu</value>
      <webElementGuid>dc470af6-ca79-4d25-80fa-87724844b915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submenu-dbbe59b56374d0128514affe177198a6&quot;)</value>
      <webElementGuid>9804fafb-1bfb-4abc-99ad-44e2ab28cf91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submenu-dbbe59b56374d0128514affe177198a6']</value>
      <webElementGuid>167868a1-b0d3-47e5-bf63-16ccfec415e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul/li[8]/div/div/div/div/a</value>
      <webElementGuid>cbee9b40-26d2-43f7-9949-64acd7015bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add new sub menu')])[8]</value>
      <webElementGuid>c6713143-69d8-487d-9326-12a2cd570dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[26]/following::a[1]</value>
      <webElementGuid>899d71e8-fc3e-4fd7-bd52-6561a5d2e583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[26]/following::a[1]</value>
      <webElementGuid>731d0e1c-e54a-420a-93b4-314e2e7b1e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testete'])[1]/preceding::a[1]</value>
      <webElementGuid>ea1f93cc-6eb1-490d-8c81-446426e43c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::a[3]</value>
      <webElementGuid>5bc4448e-0575-4fc4-b533-8b37d8819676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[35]</value>
      <webElementGuid>174ae6b1-468b-404a-a1ad-c9c477dd9a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/div/div/div/a</value>
      <webElementGuid>d494126c-1037-4d82-8989-2b31a3302889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'submenu-dbbe59b56374d0128514affe177198a6' and @href = 'javascript:;' and (text() = 'Add new sub menu' or . = 'Add new sub menu')]</value>
      <webElementGuid>b14cbfcb-93df-4f4b-81bc-91bef4ff1dfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
