<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Active with attribute</name>
   <tag></tag>
   <elementGuidId>71290cc9-b217-4c38-8826-081b7b318450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[@class=&quot;section&quot;]/div[2]/ul[@class=&quot;sortable parent ui-sortable&quot;]/li[@class=&quot;grey-out ui-sortable-handle&quot;]/span[@class=&quot;wrapper&quot;]/div[@class=&quot;toggleInteraction&quot;]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/form[@id=&quot;deactiveForm&quot;]/button[@id=&quot;deactiveBtn&quot;][count(. | //button[@id = 'deactiveBtn' and @class = 'dropdown-item' and (text() = 'Active' or . = 'Active')]) = count(//button[@id = 'deactiveBtn' and @class = 'dropdown-item' and (text() = 'Active' or . = 'Active')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='deactiveBtn'])[46]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-menu.dropdown-menu-right.show > #deactiveForm > #deactiveBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Active&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2bbb003-e390-4d05-a68c-db847b02037b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deactiveBtn</value>
      <webElementGuid>d9f31a93-f244-41f9-9fdf-768a6f616a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba69cf95-f788-4e08-86c0-dea921456a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>054ddbc9-e0e1-46f5-934a-0409d243c676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>5b859aaa-4283-43cb-b84d-180867474fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;section&quot;]/div[2]/ul[@class=&quot;sortable parent ui-sortable&quot;]/li[@class=&quot;grey-out ui-sortable-handle&quot;]/span[@class=&quot;wrapper&quot;]/div[@class=&quot;toggleInteraction&quot;]/div[@class=&quot;dropdown show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/form[@id=&quot;deactiveForm&quot;]/button[@id=&quot;deactiveBtn&quot;]</value>
      <webElementGuid>66ae560b-6e3e-4b9a-93a8-6b65c3657938</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='deactiveBtn'])[46]</value>
      <webElementGuid>359368da-4c20-4990-9a0c-7f36615a20ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='deactiveForm']/button)[46]</value>
      <webElementGuid>a228fe69-67e1-45c8-a447-871f87be64ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@#$@#&amp;($%&amp;)@'])[3]/following::button[1]</value>
      <webElementGuid>689ea1e3-1e97-4c23-bce6-9885107a06d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add new sub menu'])[19]/following::button[1]</value>
      <webElementGuid>57ee14b3-2f97-4f3a-8f51-0b497ac73df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[46]/preceding::button[1]</value>
      <webElementGuid>1cab76a1-39db-4ad1-87b8-30d6a664877b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[46]/preceding::button[1]</value>
      <webElementGuid>69db2166-11c6-4e25-b853-bc166e88785f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[20]/span/div/div/div/form/button</value>
      <webElementGuid>70ff689e-6227-43a3-a5ee-22bfd388b99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deactiveBtn' and @type = 'submit' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>1ec3c015-8f3d-44f0-8ed1-3b9a3078ff2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
