<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Menu title_input0idtitle</name>
   <tag></tag>
   <elementGuidId>d903e557-1b81-4df4-91f4-66b9ceddc892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='title-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#title-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Menu title&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fb66826-0761-461c-80cb-3148a38cf2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68d33df3-d1af-435f-a2e1-1ce1632e49d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title-id</value>
      <webElementGuid>6f33fedd-8ec6-4984-ab92-b7a95318b22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Title</value>
      <webElementGuid>32f141a8-b6fc-412f-92b8-f2ce06e2dfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>061aba93-02a0-47f4-985d-028a21ecee9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[A-Za-z0-9]+</value>
      <webElementGuid>719c5d7f-45ba-4a60-9223-213e5307348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateInput(this)</value>
      <webElementGuid>46e2e904-c4ec-43f6-8d65-06584c39eb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input[0][id][title]</value>
      <webElementGuid>341e18f2-5a99-4e26-baf1-2b1232989125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-title </value>
      <webElementGuid>c7b925c7-bb23-43e0-9742-a396c7c7bcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title-id&quot;)</value>
      <webElementGuid>88bf0b25-3269-4f63-80b7-b2caea8a4ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='title-id']</value>
      <webElementGuid>30cf0fb5-ee7c-4ca7-b0f4-94e95a28a01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-title-id-tab']/div/div/div/input</value>
      <webElementGuid>880a9180-97ff-4f62-98c1-75ce64872940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/form/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>37236279-6fe8-4b76-874c-0906d44b5adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'title-id' and @placeholder = 'Input Title' and @name = 'input[0][id][title]']</value>
      <webElementGuid>bc205ac5-a0d9-4bd0-8e16-094d05bee243</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
