<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sparepart_action</name>
   <tag></tag>
   <elementGuidId>9f0ff028-1534-4fa9-9bf7-e7495eb60d26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;table-part-list-qr-code&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;dt-center sorting_1&quot;]/input[@class=&quot;row-checkbox&quot;][count(. | //*[@type = 'checkbox' and @name = 'action']) = count(//*[@type = 'checkbox' and @name = 'action'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='action'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;CBZAFPNF00011017 Panel Front Sparepart&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33d93cbb-744d-4a06-85f1-eb3cd08e13cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b2e551d9-8987-4cdd-bab6-071baa7a400b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>0d1c300e-00e6-4bb6-8056-ccc2f603eae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-checkbox</value>
      <webElementGuid>335085c7-39f7-4232-959f-f8659714ddb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-part-list-qr-code&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;dt-center sorting_1&quot;]/input[@class=&quot;row-checkbox&quot;]</value>
      <webElementGuid>a185493f-4970-4e26-8ae3-0a669ed731db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='action'])[6]</value>
      <webElementGuid>ac4e92fd-d8d9-4fb2-b796-8b8412f781b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-part-list-qr-code']/tbody/tr[6]/td/input</value>
      <webElementGuid>de9e9b03-1aff-40de-9d54-bad64bcd35e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>db470e95-ad89-49f9-9e0c-4441b2a673d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'action']</value>
      <webElementGuid>e03fba04-37ef-438a-b200-c3ca60d2a9fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
