<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sleman, Jawa Tengah_next-testimoni</name>
   <tag></tag>
   <elementGuidId>e149ea54-485a-4b59-8ba9-d4a602091f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next-testimoni</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next-testimoni']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#next-testimoni</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d8444522-a7f1-488e-bfc5-dfdb923fd9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99acd43b-88be-41e0-a295-a2e3c11ebb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>next-testimoni</value>
      <webElementGuid>e89674d4-e00c-4272-9f7d-950abe1eb278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slick-custom-arrow slick-next slick-arrow</value>
      <webElementGuid>61a2b59d-bd41-4e81-baa1-30301aac8b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next-testimoni&quot;)</value>
      <webElementGuid>f20ad1fb-0772-497e-8d18-a3f01fdad206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='next-testimoni']</value>
      <webElementGuid>b76a28bf-4716-4e0b-b2b4-e773e9a7574c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sleman, Jawa Tengah.'])[1]/following::button[2]</value>
      <webElementGuid>718ed444-c856-447a-85bf-b482a5f5b0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah Tinggal - Sistem On-Grid 4,4kWp.'])[1]/following::button[2]</value>
      <webElementGuid>dcd3b976-e8e4-4954-9a51-f46cf66bd4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portofolio Bisnis'])[1]/preceding::button[1]</value>
      <webElementGuid>7e368c89-6930-49ad-b24c-f2a792cf6521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portofolio Bisnis'])[2]/preceding::button[1]</value>
      <webElementGuid>5a93d0ab-ab91-4a58-b35e-935add673903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f2f5e97a-7f82-4921-ac03-95475473f49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'next-testimoni']</value>
      <webElementGuid>62f9722d-24f4-4f96-8744-c85487c98562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
