<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_-_m-71</name>
   <tag></tag>
   <elementGuidId>22cef301-aa8c-4cd5-8b97-f0315d152465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question-list']/div[2]/div[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.-_m-71</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1.NamaSingle line text.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13ec084f-2788-4afd-9285-45f3d4a9841d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Single line text</value>
      <webElementGuid>b13ba1da-9da5-4f56-8059-32fe4e48d2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>23a6c4a2-4198-496c-9150-70b8047f97c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your answer</value>
      <webElementGuid>417e05bd-0a9a-426e-9cb8-f848bae3f308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QuestionId_rf6bbbbfd42944efa8353fe0e66826a4b QuestionInfo_rf6bbbbfd42944efa8353fe0e66826a4b</value>
      <webElementGuid>b77ccfe4-d145-435a-809d-67309513fea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-_m-71</value>
      <webElementGuid>0cc59f31-afc9-4ee7-94d5-deeb91a51abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eca4b75d-b230-4435-baa3-e0579e5c8a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>89af2528-ed47-4ce7-b227-fbd6271bd8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question-list&quot;)/div[@class=&quot;css-55&quot;]/div[@class=&quot;-cj-49&quot;]/div[@class=&quot;-a-65 lrp-text-container&quot;]/span[@class=&quot;-nB-72&quot;]/input[@class=&quot;-_m-71&quot;]</value>
      <webElementGuid>20a7d738-223e-46f2-81f6-2b8fa2757033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question-list']/div[2]/div[2]/div/span/input</value>
      <webElementGuid>d44cc4e1-7859-4ea6-a866-4020d54d870f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>930b06c0-4493-40c6-a6ea-81749596df24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your answer']</value>
      <webElementGuid>aa16d1a4-5b80-49de-a7c5-2fc7f49e31d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
