<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_16.716.7</name>
   <tag></tag>
   <elementGuidId>ffac7e2c-3eaf-432e-add7-87fa6eee76f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='16.7%']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.highcharts-label.highcharts-data-label.highcharts-data-label-color-0 > text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d301d7e1-9e1a-4020-9a39-473271d5efbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d87c2134-1747-4f2d-9c74-f25623174327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9cd218f3-d170-4ef0-a8c7-e404396342d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>ae96b8ab-bacf-4223-9363-7925f2f9be72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16.7%​16.7%</value>
      <webElementGuid>b655ed50-525f-4487-8f02-9f174cb30a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-zinopwx-17&quot;)/svg[@class=&quot;highcharts-root&quot;]/g[@class=&quot;highcharts-data-labels highcharts-series-0 highcharts-pie-series highcharts-tracker highcharts-series-hover&quot;]/g[@class=&quot;highcharts-label highcharts-data-label highcharts-data-label-color-0&quot;]/text[1]</value>
      <webElementGuid>6ba4414e-2f0a-423d-97c9-c762052488ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16.7%']/parent::*</value>
      <webElementGuid>b8cdc85b-2ac5-40b3-993a-f286b4187715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//text[(text() = '16.7%​16.7%' or . = '16.7%​16.7%')]</value>
      <webElementGuid>62c35838-b465-46f8-bb7c-17600d626047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
