<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer_name</name>
   <tag></tag>
   <elementGuidId>496805ec-5725-461f-834f-1dd94a276056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customer_name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customer_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7be31813-4eb5-4c17-8f02-292716e054ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05587ff9-3e53-46dc-b217-ea1103596322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_name</value>
      <webElementGuid>bb51b437-5cef-4cdf-949a-09b0cfcadebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs </value>
      <webElementGuid>9510784e-2246-4b34-b1f6-7092e4562d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Customer</value>
      <webElementGuid>c8bfd04d-9692-4d46-9d29-e5310b18b18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;body full&quot;]/div[@class=&quot;wrapper_all&quot;]/div[@class=&quot;wrapper_content&quot;]/div[2]/div[@class=&quot;detail_wrap_main__jAM1f&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-12&quot;]/div[@class=&quot;detail_wrap_form2__4g2Yy&quot;]/div[@class=&quot;detail_wrapper_form__YTXW1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs&quot;]</value>
      <webElementGuid>06cb248d-9ed2-472f-b0a2-2aadc35b9677</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customer_name']</value>
      <webElementGuid>f97803bb-d637-447c-9e04-b6e4297663c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/form/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>bb6e29dc-6f4a-4880-954a-9fdc8c2702fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>467af866-20cf-480a-be50-cc0f9de00d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer_name' and @placeholder = 'Select Customer']</value>
      <webElementGuid>45fb236b-b92e-426b-9859-795e8676afda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
