<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_navigate_next</name>
   <tag></tag>
   <elementGuidId>c5fbe580-7af6-43d2-ad35-9dfac5b5fb24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mTableId_5105885']/div[5]/div[2]/div/div/button[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;navigate_next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7375c7d6-687f-48e6-a39d-59e727e63f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons</value>
      <webElementGuid>3d79bc4c-84b1-45c5-9688-9bd1ba17bf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>navigate_next</value>
      <webElementGuid>8e22af23-2671-4ac6-9c0d-6ec3025d4acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mTableId_5105885&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12&quot;]/div[@class=&quot;row justify-content-end&quot;]/div[1]/button[@class=&quot;btn btn-sm btn-paging-nav&quot;]/i[@class=&quot;material-icons&quot;]</value>
      <webElementGuid>10b2b526-173a-487a-ab17-29dfc116fdce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_5105885']/div[5]/div[2]/div/div/button[4]/i</value>
      <webElementGuid>ea325d74-21c7-410a-91db-ef8d4e98a04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_before'])[1]/following::i[1]</value>
      <webElementGuid>d4e18e48-b6e5-4dcc-a8d2-38f63b4b7fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO TO PAGE'])[1]/following::i[2]</value>
      <webElementGuid>9ec22e01-887c-4d39-ad10-e11a386d7ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='navigate_next']/parent::*</value>
      <webElementGuid>97c9ae3e-73d5-426a-a909-90d926c42869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]/i</value>
      <webElementGuid>5344914e-b8cc-4dd8-a497-664a528e0831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'navigate_next' or . = 'navigate_next')]</value>
      <webElementGuid>d59e91fd-ef56-47b9-9cfc-deb29b799400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
