<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete (2)</name>
   <tag></tag>
   <elementGuidId>489c6373-c170-4939-af8b-d7cca1de2567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a1542a9-63bd-4e01-861d-274c5acc1e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      <webElementGuid>f78db24c-ba08-40b3-84c9-6424ca5ade45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>790c5367-f81d-4ff4-b71f-72471a626089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete-header subHeaderBtn dropdown-item</value>
      <webElementGuid>87141c5c-7db9-4fa7-ae00-5080d6545979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>a6f5d07d-09ac-4477-b255-2c089da684ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2&quot;)</value>
      <webElementGuid>17c778d4-03a7-4ac1-8e60-a639189df4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      <webElementGuid>da3ee0dc-846c-41aa-80e8-3976849f7929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul/li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>3384f0b0-6fa9-4beb-b614-cb7d1e988d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[28]/following::button[1]</value>
      <webElementGuid>2ac46468-f089-4c98-b7e1-eccbf9c7255e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[28]/following::button[1]</value>
      <webElementGuid>d58a33d3-7c46-4f91-a6df-42f7492d82b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporasi Nihonggo'])[2]/preceding::button[1]</value>
      <webElementGuid>b9d2489a-6ea8-4777-9f5e-1d824cd5b481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[29]/preceding::button[1]</value>
      <webElementGuid>549d2c69-23fe-4be0-89b3-ccf8786142bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>f7e408a9-a989-4dfb-b26c-95e88b15c961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2' and @type = 'submit' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>f70d0fd4-7a69-4490-8d55-9754873a631e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
