<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>bb031479-8c3a-4f4b-b946-555b6b4bc6b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa3fa746-a730-4054-a4a9-17aac76da2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2</value>
      <webElementGuid>035b93aa-576f-4d30-929e-a3d61d35a69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>67783312-ccd1-47d0-bef5-c85477e6b38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-delete-header subHeaderBtn dropdown-item</value>
      <webElementGuid>ff10adef-6c12-4e36-91b7-cc9e55e3eb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>2a27e1e5-ad84-4492-80c5-ac68e7a1ba5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2&quot;)</value>
      <webElementGuid>608d756a-3d8c-4ab4-9201-b886458d70c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2']</value>
      <webElementGuid>73e68aff-eecc-4fe2-9378-9db8a418bdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/ul/li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>30d51d80-5eb7-4dae-8812-26795b30614b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[28]/following::button[1]</value>
      <webElementGuid>b9b15694-5453-43a0-9a9c-a9cb7c2a1fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[28]/following::button[1]</value>
      <webElementGuid>6943912e-df5f-4cdb-ba3e-24ee1b2656f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporasi Nihonggo'])[2]/preceding::button[1]</value>
      <webElementGuid>d615ab90-b559-4658-b3ab-20493e3dddc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactive'])[29]/preceding::button[1]</value>
      <webElementGuid>9764dc09-17a8-4651-a8b5-5771d802493b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/ul/li[2]/span/div/div/div/button</value>
      <webElementGuid>83edb9e0-671f-489a-a81e-04c73b4bdc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deleteBtnChild-b730961af5aa8ab8d0a786519d0409d2' and @type = 'submit' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>600c50a4-5bc5-4aff-901f-063e91532f10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
