<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DSC</name>
   <tag></tag>
   <elementGuidId>51e03321-39dd-466b-8150-86701a652ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown.p-component.p-inputwrapper.p-inputwrapper-filled.flex-1 > span.p-dropdown-label.p-inputtext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='add-service-area_content']/div[2]/div/div/div[3]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39d5895b-be3d-49c6-9106-3237f066f3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-label p-inputtext</value>
      <webElementGuid>f0643988-6226-4d59-b698-f3ed0418d829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DSC</value>
      <webElementGuid>874a70d5-8ec0-4ae8-98a8-91d51329d278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-service-area_content&quot;)/div[@class=&quot;flex-1&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;mx-2 my-5  flex align-items-center&quot;]/div[@class=&quot;flex-1 flex&quot;]/div[@class=&quot;p-dropdown p-component p-inputwrapper p-inputwrapper-filled flex-1&quot;]/span[@class=&quot;p-dropdown-label p-inputtext&quot;]</value>
      <webElementGuid>cc0d093a-06f3-4cfc-98c2-f112ad591a27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='add-service-area_content']/div[2]/div/div/div[3]/div[2]/div/span</value>
      <webElementGuid>7da4ea31-a600-4190-8dc6-85afd914bb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Center Type'])[12]/following::span[1]</value>
      <webElementGuid>d778bd06-7991-424f-94c0-c6a0d2bde701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Area Name'])[1]/following::span[1]</value>
      <webElementGuid>6ff155f5-1d6f-4baf-ad00-8ecdd7ecbad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Type'])[12]/preceding::span[2]</value>
      <webElementGuid>19e934a3-67a5-4591-b044-91eebaff804a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AP'])[8]/preceding::span[2]</value>
      <webElementGuid>4765f8a3-f988-4245-9997-29e4daf00140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/span</value>
      <webElementGuid>803afc55-b781-4b52-a84f-86227c3f8474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DSC' or . = 'DSC')]</value>
      <webElementGuid>beed60ff-12a8-48fc-af88-104242c09a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
