<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sparepart_action</name>
   <tag></tag>
   <elementGuidId>0cae2cd0-7d58-4a44-bb86-44b4f78f477a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;table-part-list-qr-code&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;dt-center sorting_1&quot;]/input[@class=&quot;row-checkbox&quot;][count(. | //*[@type = 'checkbox' and @name = 'action']) = count(//*[@type = 'checkbox' and @name = 'action'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='action'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;CBZAFPNF00011017 Panel Front Sparepart&quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a925a7f6-58d1-4303-ba4c-671323c494a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1a9ca5a3-f1d3-4589-8a4f-2ba36ea1e03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action</value>
      <webElementGuid>2c724c24-7271-4c92-b7d7-97c6d37c678b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row-checkbox</value>
      <webElementGuid>3f823f69-c6a1-4295-8d54-422cf7db7890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-part-list-qr-code&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[@class=&quot;dt-center sorting_1&quot;]/input[@class=&quot;row-checkbox&quot;]</value>
      <webElementGuid>cb9ca9e4-77f3-4433-a3b1-9e6b7f9de231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='action'])[6]</value>
      <webElementGuid>dae25043-40ed-4b72-990f-0b62f8679b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-part-list-qr-code']/tbody/tr[6]/td/input</value>
      <webElementGuid>629f1b76-3032-4cc0-af04-362992753a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>9b179257-68f2-45cb-89a2-fecd855d892a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'action']</value>
      <webElementGuid>b404e137-2654-45f3-9eda-0e334ec1b1cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
