<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty_checkbox-action</name>
   <tag></tag>
   <elementGuidId>924fd4c5-fe2f-40f2-a546-f3f5a16078ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.checkbox-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[26]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;CBZ-AD-DOR-0002-0118 DOOR&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffdc00b1-9dab-4c15-94fb-30d63111c982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ef5189fd-3a86-45c1-8d70-50f0c04f8b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-action</value>
      <webElementGuid>c8d93894-87cb-4f0e-bffb-1dcde2d7e04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-part-list-copied&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;dt-center sorting_1&quot;]/input[@class=&quot;checkbox-action&quot;]</value>
      <webElementGuid>e54a19d7-71f5-46d3-8e17-eeb6cc72bb0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[26]</value>
      <webElementGuid>5d96bc24-ac3e-4552-886b-c24e0ce331bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-part-list-copied']/tbody/tr/td/input</value>
      <webElementGuid>58a075e6-f797-4b71-9dcc-04188a60f75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7685435e-ece9-4556-9fb3-0caee48844b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c459a09e-7964-46c5-81a0-e0997ecb8d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
