<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_W_dim_d</name>
   <tag></tag>
   <elementGuidId>457b3c41-aed4-46a1-a69f-e79f9da43865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim_d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim_d']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dim_d</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e01d0322-d38f-4c48-87d4-1c82a1f0564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim_d</value>
      <webElementGuid>f63bc428-948a-4e42-be56-30d822bce749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dim_d</value>
      <webElementGuid>17a9a454-a403-4238-a00e-d8ca104559ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>63245cb2-4384-43f2-b4e3-ab839a037843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00963124-cb9b-45fd-81d0-0a3142608e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim_d&quot;)</value>
      <webElementGuid>16c0647f-dcda-4487-8cf2-5f2a00bd17cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim_d']</value>
      <webElementGuid>473a2c87-3c17-4dce-b023-43532bd94520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[5]/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>b18ed0c0-306a-46cf-9c26-4d3151332f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[2]/input</value>
      <webElementGuid>085fc7d4-1636-430b-b8f7-10cc7f047e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dim_d' and @name = 'dim_d' and @type = 'text']</value>
      <webElementGuid>7c5c8c81-fd26-4d50-a4b2-9d0150887591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
