<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Select a base classification --</name>
   <tag></tag>
   <elementGuidId>6000f894-18af-4667-b724-f46354ac0bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-base_id-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-base_id-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;-- Select a base classification --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>36fa62da-7d84-4a82-b62c-7b67068fb81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>edd56f22-ec76-42f4-a578-b0ae89bbaa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-base_id-container</value>
      <webElementGuid>703158f8-472d-4569-a83e-dfba0c79c99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Select a base classification --</value>
      <webElementGuid>aa213dd2-626c-4763-ad29-53c656509820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select a base classification --</value>
      <webElementGuid>2de4987f-d86c-451f-9490-7d2ec718c160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-base_id-container&quot;)</value>
      <webElementGuid>e46396ca-5f03-40f6-aa3a-3e2412b0f8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-base_id-container']</value>
      <webElementGuid>537667aa-f048-4872-9a07-071302ac000c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[5]/td[2]/span/span/span/span</value>
      <webElementGuid>ff20524f-e1c9-4458-a891-4bc6ff6acf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Based Classification'])[1]/following::span[4]</value>
      <webElementGuid>3103ad43-09dd-4c24-8503-f1057e7c3df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BLAST CHILLER'])[2]/following::span[6]</value>
      <webElementGuid>030f45e7-3138-4036-ae0b-e63ee5cea9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Functional Classification'])[1]/preceding::span[3]</value>
      <webElementGuid>eb2e1757-220c-4af5-8f72-8086a06d3c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select a functional classification --'])[2]/preceding::span[3]</value>
      <webElementGuid>11905dfa-61e5-474c-ac78-47426dd3183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span/span/span/span</value>
      <webElementGuid>d549b25b-5125-45c6-bf1d-5212a29f7633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-base_id-container' and @title = '-- Select a base classification --' and (text() = '-- Select a base classification --' or . = '-- Select a base classification --')]</value>
      <webElementGuid>c35818aa-9491-4c66-8b6c-b0e9dc3cc538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
