<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identity_type</name>
   <tag></tag>
   <elementGuidId>007b9c55-1f82-4c72-b8b6-1e654632511f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Identity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;identity_type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6be31637-8c8c-4c27-aef5-7972794d10fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a41619fb-ffb7-408e-bf00-5c4f8cfc92d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identity_type</value>
      <webElementGuid>7c8c7147-f139-4337-820e-5bf25bd3b721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs </value>
      <webElementGuid>50931d58-c04e-4bc1-aae2-416b3e4fec86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Identity</value>
      <webElementGuid>5345bf92-0338-481b-bdf0-2a6cd5512eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;body full&quot;]/div[@class=&quot;wrapper_all&quot;]/div[@class=&quot;wrapper_content&quot;]/div[2]/div[@class=&quot;detail_wrap_main__jAM1f&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-12&quot;]/div[@class=&quot;detail_wrap_form2__4g2Yy&quot;]/div[@class=&quot;detail_wrapper_form__YTXW1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs&quot;]</value>
      <webElementGuid>3e3c4792-2d76-4718-9e23-77830775fd26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='identity_type']</value>
      <webElementGuid>ceab2f2e-3f32-458d-97ac-f7e98e29f2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/form/div/div/div/div/div[6]/div/div[2]/div/input</value>
      <webElementGuid>a0144665-f16e-4821-a57f-2b8d77a83b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/input</value>
      <webElementGuid>1d505a24-c1eb-49ae-97dd-4f93b0b5e010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'identity_type' and @placeholder = 'Identity']</value>
      <webElementGuid>944bc6b1-ebd9-4075-b2ee-e2d20c30552a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
