<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_GG001 - MODENA PRO GAS STOVE</name>
   <tag></tag>
   <elementGuidId>47ba419f-611f-4ea1-8a00-0a25bff20af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='SR001 - MODENA PRO SALADETTE RANGE'])[1]/following::li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ce22618d-e7bd-405a-8f8b-0d7976d86bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-item</value>
      <webElementGuid>74f25eb0-f6db-4547-8450-975f4360d2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>GG001 - MODENA PRO GAS STOVE</value>
      <webElementGuid>d7d4e365-e18c-4b6e-b73f-b4d962a6343c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>82bd233d-bde6-4d7a-a5ad-f43c83dcc0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37a25dd6-d114-4962-9f5d-06d6b45f11a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GG001 - MODENA PRO GAS STOVE</value>
      <webElementGuid>dc4ff310-fb28-4205-935d-29390bb42800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;p-dropdown-panel p-component p-connected-overlay-enter-done&quot;]/div[@class=&quot;p-dropdown-items-wrapper&quot;]/ul[@class=&quot;p-dropdown-items&quot;]/li[@class=&quot;p-dropdown-item&quot;]</value>
      <webElementGuid>ee70fe8b-8746-468f-b6d1-3c53d83c2d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SR001 - MODENA PRO SALADETTE RANGE'])[1]/following::li[2]</value>
      <webElementGuid>3f1f8611-b29f-4ced-8450-5363788a2790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT002 - MODENA PRO ELECTRIC GRIDDLE'])[1]/preceding::li[1]</value>
      <webElementGuid>a2eed6fa-d2cf-458e-8886-e16ca31bdaed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DQ001 - DOMO PORTABLE MULTI GRILL'])[1]/preceding::li[2]</value>
      <webElementGuid>807ab23d-b78f-4c9b-b948-514d45a0916f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[82]</value>
      <webElementGuid>a72e62c8-c7bd-442f-90bc-58273be8c3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'GG001 - MODENA PRO GAS STOVE' or . = 'GG001 - MODENA PRO GAS STOVE')]</value>
      <webElementGuid>0fb07d1e-a7ba-4f6d-95b6-707618f6c3eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
