<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-- Select a branch -- (1)</name>
   <tag></tag>
   <elementGuidId>4b85f6b7-64d8-46ab-b353-2384e1a280f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-branch_id-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-branch_id-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;-- Select a branch --&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1ed4e5f-f104-4ad8-8f69-a341d3b59028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2b652610-85c1-4f2a-a409-feef987bbada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-branch_id-container</value>
      <webElementGuid>20f848a4-5817-4a55-9303-1ec823d6866a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Select a branch --</value>
      <webElementGuid>58a23bb6-2c63-45c9-a1fc-7f9c4f4cdb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Select a branch --</value>
      <webElementGuid>36155e10-b019-43c5-96d6-e8d1ce2cab95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-branch_id-container&quot;)</value>
      <webElementGuid>be741656-534e-4449-bfe3-152eb27b7c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-branch_id-container']</value>
      <webElementGuid>862b7d82-c49a-435b-8961-e5acf20441e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-other-org-stock']/thead/tr[2]/td[2]/span/span/span/span</value>
      <webElementGuid>47f4b6a9-7bbe-4f4b-a2f0-7e7a64f9b2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Branch'])[1]/following::span[4]</value>
      <webElementGuid>3e6092ea-dd41-48d5-9757-8a7fa3fcf6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Select a segment --'])[2]/following::span[6]</value>
      <webElementGuid>ef8c1120-1efa-49f0-9ad3-e0b148ebcfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Group'])[1]/preceding::span[3]</value>
      <webElementGuid>ee5f39d9-93df-4404-8773-39fe73445221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span/span/span/span</value>
      <webElementGuid>ab5ae93e-19dc-47a0-b71c-5b3dbc5d041f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-branch_id-container' and @title = '-- Select a branch --' and (text() = '-- Select a branch --' or . = '-- Select a branch --')]</value>
      <webElementGuid>b2196a5d-7e48-449b-8bb2-41cb75d3fb85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
