<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Length (mm)_cut_out_length</name>
   <tag></tag>
   <elementGuidId>68c06706-466b-461e-9e32-b9a7f373d806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_length</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cut Out Length (mm)&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1cd2cb0-0af1-46be-83c6-550971078f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_length</value>
      <webElementGuid>ad00e735-98da-4413-bd78-75f563ffb8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_length</value>
      <webElementGuid>4626add8-7292-4aa2-a3ec-6c7aa3ef5de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af26e62d-ba33-4b7d-b659-5306c57943cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cut Out Length (mm)</value>
      <webElementGuid>1ada2ff0-47e9-4f07-aef1-f823994f8ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a9737451-4042-4a11-a154-9f1485f64253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_length&quot;)</value>
      <webElementGuid>d8ddedf9-6afe-44a6-8ad2-11e3e5aa7dcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_length']</value>
      <webElementGuid>e0841943-10d4-49f2-9028-fbe0a84ac5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>96025dbe-bcc2-4615-8f9f-9266ce74d32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/input</value>
      <webElementGuid>797a17f8-eda1-4a0e-b60f-2ac25a841d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_length' and @name = 'cut_out_length' and @type = 'text' and @placeholder = 'Cut Out Length (mm)']</value>
      <webElementGuid>2ff0c7f3-8341-425f-92e7-b4323517dcaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
