<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kompensasi</name>
   <tag></tag>
   <elementGuidId>fa46d7ac-3247-45f3-b1ee-c234dbe59fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-category']/div/div/div[2]/div/section/div/div/div/ul/li[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;📁Kompensasi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f59077b7-b9aa-42ff-ab04-1af28df5090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>📁Kompensasi</value>
      <webElementGuid>6e2e4249-69ce-4603-8196-76f49dd715ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-category&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow mb-4&quot;]/div[@class=&quot;card-body&quot;]/ul[@class=&quot;categories-list&quot;]/li[2]/div[1]/div[1]</value>
      <webElementGuid>d4b98094-98eb-4152-b07b-62c464615c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-category']/div/div/div[2]/div/section/div/div/div/ul/li[2]/div/div</value>
      <webElementGuid>f0a7aa79-6294-49d4-beea-13940bda674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📁'])[1]/following::div[2]</value>
      <webElementGuid>bf7c7305-51a5-48d7-97c8-78cd3cea0250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kompensasi']/parent::*</value>
      <webElementGuid>df568167-e773-4798-a1b2-a05db428a293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div</value>
      <webElementGuid>7092c855-4bf5-4acf-847c-abe6eab3a345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '📁Kompensasi' or . = '📁Kompensasi')]</value>
      <webElementGuid>8557f5e1-c4eb-4792-b5da-eea206b90c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
