<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pick this category</name>
   <tag></tag>
   <elementGuidId>2f59529e-041a-4348-b982-e6af2678431d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-category']/div/div/div[2]/div/section/div/div/div/ul/li[2]/ul/li/ul/li/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pick this category&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2fe191dd-591d-4805-be5d-12ea18ae861a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sd-proper-text</value>
      <webElementGuid>6e555d1a-7b41-448f-b926-3d8333afa234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick this category</value>
      <webElementGuid>8f370a4f-7496-448d-b835-dfffe80dedd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-category&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;card shadow mb-4&quot;]/div[@class=&quot;card-body&quot;]/ul[@class=&quot;categories-list&quot;]/li[2]/ul[@class=&quot;categories-list&quot;]/li[1]/ul[@class=&quot;categories-list&quot;]/li[1]/div[1]/div[2]/div[@class=&quot;sd-proper-text&quot;]</value>
      <webElementGuid>a1fd3708-7d58-42a3-861c-123e569b1f1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-category']/div/div/div[2]/div/section/div/div/div/ul/li[2]/ul/li/ul/li/div/div[2]/div[2]</value>
      <webElementGuid>637c4b8a-00a8-4986-97eb-cedb293dc7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📁'])[2]/following::div[3]</value>
      <webElementGuid>93ed23b6-3485-4983-835d-9bdba844ac09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='📁'])[3]/preceding::div[1]</value>
      <webElementGuid>f4384c61-23a3-4020-b2d9-62fdda65971a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pick this category']/parent::*</value>
      <webElementGuid>18f1d84a-88f8-4d10-8510-4ea6e5df0a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>79daf85b-9629-4881-9afe-1bf53d49f718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pick this category' or . = 'Pick this category')]</value>
      <webElementGuid>aab58016-2251-42b6-ae30-776e3a12a7bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
