<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select fieldPR NumberPO NumberPO Dat_ce0b89</name>
   <tag></tag>
   <elementGuidId>53a4c606-bd10-4197-b218-a9be9c832d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;filter_field&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='filter_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;filter_field&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8a04140f-df67-42dd-b30b-3f4187c17f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-0</value>
      <webElementGuid>e31e2ab2-a38b-48e9-baee-6e4f1976cbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filter_field</value>
      <webElementGuid>31c4ee30-5933-4393-add2-0f3d74d150d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select fieldPR NumberPO NumberPO DatePR Need DateSupplier NameSummary of PurchasesRequestor NameDepartmentTotal Value</value>
      <webElementGuid>97ba7f66-ce75-44fb-9230-57d299ae7b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mTableId_4083998_filter&quot;)/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;d-flex&quot;]/div[1]/select[@class=&quot;form-control rounded-0&quot;]</value>
      <webElementGuid>e46031b5-22cf-4737-b74a-5aa1b8c517bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='filter_field']</value>
      <webElementGuid>1828b517-9055-495c-bdf0-f3169b338734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_4083998_filter']/div/div[2]/div/div/select</value>
      <webElementGuid>a310e64c-ade2-4a9b-9037-cae40f011880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::select[1]</value>
      <webElementGuid>a0c983c7-1f18-4148-aaef-7090dc090000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Goods Receipt'])[1]/following::select[1]</value>
      <webElementGuid>d65d82b9-956d-47c2-8eb0-9497a5d01af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::select[1]</value>
      <webElementGuid>d716d43e-03bc-4eba-b3e9-5f55c6bbb244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[2]/preceding::select[1]</value>
      <webElementGuid>7a4dce85-f159-4de1-9d4b-bba5b16bf7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f1bdbe66-8fa2-4e35-8667-9032d70941fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'filter_field' and (text() = 'Select fieldPR NumberPO NumberPO DatePR Need DateSupplier NameSummary of PurchasesRequestor NameDepartmentTotal Value' or . = 'Select fieldPR NumberPO NumberPO DatePR Need DateSupplier NameSummary of PurchasesRequestor NameDepartmentTotal Value')]</value>
      <webElementGuid>79608406-072a-47f3-b22a-e550d78815c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
