<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Outer Weight (kg)_outer_weight</name>
   <tag></tag>
   <elementGuidId>9025fd56-1294-4cb5-b633-2ac98afc5825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='outer_weight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outer_weight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Outer Weight (kg)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b287573d-2d03-4f8b-ac5a-bf56e07a6da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outer_weight</value>
      <webElementGuid>30bd454a-4cfe-4db0-9e8a-e0d351fa5520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>outer_weight</value>
      <webElementGuid>75be8296-3915-49c9-b6c9-46a558f09f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d13f40ca-82a3-4c98-b5eb-c7afa88da399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Outer Weight (kg)</value>
      <webElementGuid>55b3edae-1a8d-41d8-a0b2-396140427e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>38d6b64d-3fc0-49a9-a199-25764f8633d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outer_weight&quot;)</value>
      <webElementGuid>0128c971-bea6-43d8-be1b-5b6b01a21646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outer_weight']</value>
      <webElementGuid>862d8754-6d37-4492-85a4-2c515f446f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[2]/div[2]/div[5]/input</value>
      <webElementGuid>6c324760-900d-4f8f-9f23-db33250ce6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[5]/input</value>
      <webElementGuid>effc8d35-cbfb-4d33-a563-047d74508a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outer_weight' and @name = 'outer_weight' and @type = 'text' and @placeholder = 'Outer Weight (kg)']</value>
      <webElementGuid>795ccce6-a6b5-412e-b2bb-106594e3a202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
