<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height (mm)_cut_out_height</name>
   <tag></tag>
   <elementGuidId>a86d6042-dd42-4cef-813d-69315a4191d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_height']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_height</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cut Out Height (mm)&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f69f116-3aec-477b-b12c-8f0929cd8dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_height</value>
      <webElementGuid>42b2ed1c-f13a-42d2-bd28-3619d8bbaffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_height</value>
      <webElementGuid>c617e62e-484e-4592-a3a6-95e1f0ba758d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0e508f6-c176-460a-ac45-acd4e21cd9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cut Out Height (mm)</value>
      <webElementGuid>69abe359-9704-4eda-a6d5-9a538f935198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6b360532-76f7-469e-aed3-84da2eba9dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_height&quot;)</value>
      <webElementGuid>2c8f5e25-9e13-4284-a01e-ce380c0b40c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_height']</value>
      <webElementGuid>6f102ad7-c2f7-46c3-b817-dee69c05cdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>d658da81-5a2d-4408-9e3e-3141d42a38cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div[2]/div/input</value>
      <webElementGuid>f2c71682-d566-4fb6-a1ad-938aad09142e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_height' and @name = 'cut_out_height' and @type = 'text' and @placeholder = 'Cut Out Height (mm)']</value>
      <webElementGuid>b485c347-f76e-47eb-8594-d0cd01d2e18c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
