<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select GroupFG - HOME APPLIANCEFG - _be317a</name>
   <tag></tag>
   <elementGuidId>e01cd4cb-8cce-4ebd-bd73-f4d1c876f796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='group_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#group_code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#group_code</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>74fdb816-57cf-4021-b2f9-0a4193725b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>group_code</value>
      <webElementGuid>26c9d37a-eebb-40b2-a378-d1f913c4e889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>68490c90-4658-476c-afd5-b7c06b77086f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>group_code</value>
      <webElementGuid>8e735df7-788e-4d3f-bea1-e21be065566d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL</value>
      <webElementGuid>395ff018-c9d5-498a-a91d-6dd53125b286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group_code&quot;)</value>
      <webElementGuid>6ff0ff73-60d8-4682-bc72-494c61aa8772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='group_code']</value>
      <webElementGuid>8be2bb03-f1b9-4d91-bad9-4afe75ef5bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]/div[3]/select</value>
      <webElementGuid>ab020f02-7d31-48ac-9c7d-e50de0a377cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group'])[1]/following::select[1]</value>
      <webElementGuid>b7caae9b-696d-4ca0-91da-9ace7767b348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item Name'])[1]/following::select[1]</value>
      <webElementGuid>1d8c33ef-d11d-4663-9b35-ab2f886715d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supplier Code'])[1]/preceding::select[1]</value>
      <webElementGuid>33fd366c-bb64-4bf0-9097-320e4b805dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Launch Date'])[1]/preceding::select[1]</value>
      <webElementGuid>0be30dbe-291c-4a44-a143-561228a566b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/select</value>
      <webElementGuid>7e75b1a3-cc7d-475c-994d-33c31087cb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'group_code' and @name = 'group_code' and (text() = 'Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL' or . = 'Select GroupFG - HOME APPLIANCEFG - PROFESSIONAL')]</value>
      <webElementGuid>17b54cc0-c7bd-4aab-8cad-80fd648fb4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
