<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Active_Brand</name>
   <tag></tag>
   <elementGuidId>9a8239ff-ad09-4502-9b40-66f5065a184c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.p-inputswitch-slider</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div/div[2]/div/form/div/div[3]/div/div[2]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4f3c5e5-e6d3-4f42-89e4-e094878343b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputswitch-slider</value>
      <webElementGuid>8918ebd9-56af-4c2d-a0f0-9ee0e2cc80cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;col-sm-8 col-md-10 col-lg-10 col-xl-12 col-xxl-12&quot;]/div[@class=&quot;card shadow mb-3&quot;]/form[1]/div[@class=&quot;card-body&quot;]/div[@class=&quot;card__side--back-show&quot;]/div[@class=&quot;d-flex justify-content-between p-3&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;form-group&quot;]/div[1]/div[@class=&quot;p-inputswitch p-component p-inputswitch-checked&quot;]/span[@class=&quot;p-inputswitch-slider&quot;]</value>
      <webElementGuid>c745dbf7-995a-4683-9628-b2b697b26246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div[2]/div/form/div/div[3]/div/div[2]/div/div/div/span</value>
      <webElementGuid>a20b1ec3-c9b2-4c03-ac62-126b6a25c29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span</value>
      <webElementGuid>b7d31c72-229d-43d3-bbb3-1a790eb09a3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
