<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nama dealer_209</name>
   <tag></tag>
   <elementGuidId>27e48d94-7f01-432b-8f35-dbd623b90bf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#209</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;pr_id_12_content&quot;]/div[2]/div/div/div[2]/div[1]/div[2]/div[10]/div[1]&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad93d9d3-a71f-4995-8772-0b089ba3ec51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2b3966c2-eb2e-422d-9b7b-209a29b4a759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>209</value>
      <webElementGuid>d6eca4a1-45da-4430-b5a5-7536b50a2fe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>209</value>
      <webElementGuid>bee53195-a01e-4b1a-8a77-c0954d62e9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_12_content&quot;)/div[2]/div[@class=&quot;content&quot;]/div[@class=&quot;col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2&quot;]/div[2]/div[1]/div[2]/div[1]/div[1]/input[@id=&quot;209&quot;]</value>
      <webElementGuid>5ca98dba-87fd-4b6e-a5a7-1db2b2eff062</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='209']</value>
      <webElementGuid>9ba1f89f-c615-40e8-8261-004699a59bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_12_content']/div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>f7be2443-ab6f-4cf6-900e-14a06df33434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nama dealer'])[1]/following::input[1]</value>
      <webElementGuid>b2a12dc0-e4b7-4914-b2f8-b5e0a78c5b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[1]/following::input[1]</value>
      <webElementGuid>9046ecbb-8fb2-4f6d-85af-7aef199f255c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::input[1]</value>
      <webElementGuid>acd54436-a20b-4ebb-9b08-338b4bbba07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='b'])[1]/preceding::input[2]</value>
      <webElementGuid>f2762079-38e5-436e-b93b-53657f3fed56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>ffa9ea67-8ee5-408d-a8c9-6a5d6f23c1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = '209' and @name = '209']</value>
      <webElementGuid>3fe0a3d7-2382-409a-9d45-942505575db8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
