<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Length (mm)_cut_out_length_undermount</name>
   <tag></tag>
   <elementGuidId>61de400c-2295-4e94-aa1b-781c337b92ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_length_undermount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_length_undermount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Undermount Cut Out Length (mm)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4a7dc52-aecb-4712-8676-dbc69d36eb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_length_undermount</value>
      <webElementGuid>3de194a3-924f-47d9-adfc-cb7824311958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_length_undermount</value>
      <webElementGuid>0642a666-f671-4507-a885-edbc2f713443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>463152f2-e15a-4221-9a28-f3bbb4e25654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Undermount Cut Out Length (mm)</value>
      <webElementGuid>29e665e5-0a08-43b6-9c21-2f4b48ce5623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a97cf6b7-189a-450f-989f-c9c33f45fab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_length_undermount&quot;)</value>
      <webElementGuid>0d8c67ff-6fab-427d-8938-3d3d12a0b2e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_length_undermount']</value>
      <webElementGuid>718b6cfc-f778-4123-82ef-2063c5c7d2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[5]/div[2]/div[3]/input</value>
      <webElementGuid>53d91362-6507-4ebe-9ed3-43424caa8844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[3]/input</value>
      <webElementGuid>28054f30-7705-468c-9e16-01664031942f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_length_undermount' and @name = 'cut_out_length_undermount' and @type = 'text' and @placeholder = 'Undermount Cut Out Length (mm)']</value>
      <webElementGuid>02cba9f4-b990-4ee6-83e2-329852a9ece0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
