<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Depth (mm)_cut_out_depth</name>
   <tag></tag>
   <elementGuidId>083fce01-ac9a-4e5a-aa35-d06edb3bd36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_depth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_depth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Cut Out Depth (mm)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8338680c-cbc3-42f1-a019-23dab802aaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_depth</value>
      <webElementGuid>c0dcc58a-641b-4d98-af59-86708873f980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_depth</value>
      <webElementGuid>7f1bfed4-d78d-4ce2-9d47-6c23d2343e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef5e44bd-103d-4469-81c6-69658fb12ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cut Out Depth (mm)</value>
      <webElementGuid>51918807-d606-4954-b873-24ced6345ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f362d8a3-17e4-46a5-b90a-6e86d80b8831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_depth&quot;)</value>
      <webElementGuid>1be53cde-e675-4974-8110-f0e8793d2cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_depth']</value>
      <webElementGuid>4c98e205-8295-4960-b5bc-e72738500362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[3]/div[2]/div[4]/input</value>
      <webElementGuid>9fc12bee-e4cf-4846-86a5-951a8fb3c9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[4]/input</value>
      <webElementGuid>67cc606d-40e0-4776-b3a0-11641dbe2d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_depth' and @name = 'cut_out_depth' and @type = 'text' and @placeholder = 'Cut Out Depth (mm)']</value>
      <webElementGuid>a858992a-2e03-41e7-b2ed-369253f97fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
