<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Item Name_item_name</name>
   <tag></tag>
   <elementGuidId>5ca4060e-c2f9-401e-93ca-0e86dbaecaeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='item_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Item Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da98a315-f168-488c-85e8-32128ba6f454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_name</value>
      <webElementGuid>6b6a02be-a6c5-4775-8cde-acc01ba2bf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item_name</value>
      <webElementGuid>1fc6e8e6-4863-4004-97a3-8dcf6e817339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Item Name</value>
      <webElementGuid>f2d20053-c4ca-4a29-ab8b-62d36f7eba8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>866c7730-5165-4d43-9c06-33c0b23d78bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_name&quot;)</value>
      <webElementGuid>2e7ee426-4585-42cd-bc26-3ba28b7caeaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='item_name']</value>
      <webElementGuid>7054566c-0437-45a4-bfd0-ee622d2ed459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[4]/div[2]/input</value>
      <webElementGuid>4a1eecc1-b555-4afb-a1ca-9dc781732272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>25db6ebf-2f8b-4acd-8eb3-f22086dac29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'item_name' and @name = 'item_name' and @placeholder = 'Item Name']</value>
      <webElementGuid>3b6bf811-bc51-4ad5-88fa-f5d050767387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
