<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Width (mm)_cut_out_width_undermount</name>
   <tag></tag>
   <elementGuidId>c5792c1a-c340-4461-8463-5a07eae02e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cut_out_width_undermount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cut_out_width_undermount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Undermount Cut Out Width (mm)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>493a3b87-93cb-4f1a-8bc0-8d392c3d6777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cut_out_width_undermount</value>
      <webElementGuid>316dc9d7-1460-4487-9b57-33d1a4cfe3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cut_out_width_undermount</value>
      <webElementGuid>0b456e18-1fa2-4210-88b1-6a6df939b746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2df11b7a-c380-4502-9471-3c37862cc2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Undermount Cut Out Width (mm)</value>
      <webElementGuid>dc4c2915-bd42-4c53-942a-3fa7e87813d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ba9fb92d-7078-4fd3-ba03-77d9f4907ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cut_out_width_undermount&quot;)</value>
      <webElementGuid>c1eb86bc-dcd0-44cd-a8f2-3faf97528e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cut_out_width_undermount']</value>
      <webElementGuid>f2143397-c510-47c0-9a34-fc0a52cb5297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div[5]/div[2]/div[2]/input</value>
      <webElementGuid>1d5ff0c2-f804-4d07-8cb1-222e708e265c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/input</value>
      <webElementGuid>eafbd34c-cfcb-4e89-8022-5120cc8d8dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cut_out_width_undermount' and @name = 'cut_out_width_undermount' and @type = 'text' and @placeholder = 'Undermount Cut Out Width (mm)']</value>
      <webElementGuid>ac906d69-6b5d-40ec-9a24-4fd690fe6331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
