<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Weight TypeGramKG</name>
   <tag></tag>
   <elementGuidId>0a40b9e6-9ea2-4544-9f8b-085eddf45107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='weight_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weight_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#weight_type</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>40725be6-62fb-4278-b06c-3405de77a940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight_type</value>
      <webElementGuid>4a6037a1-2be0-4e7c-9838-55b13089bf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d48677af-7704-4fee-8839-408a7a2d4502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight_type</value>
      <webElementGuid>d5baedae-33dd-4356-9e03-f8e1ef7165be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Weight TypeGramKG</value>
      <webElementGuid>37552239-2765-4bf7-966f-68d8f1e484a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight_type&quot;)</value>
      <webElementGuid>0ce7cd7c-38f3-45c4-b9e0-dd98986b9594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='weight_type']</value>
      <webElementGuid>44192963-eced-49c9-a8e3-b51aad5cd6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[4]/div/div/div[3]/div[3]/select</value>
      <webElementGuid>54402e58-d352-41c9-aa9d-c3dba30730a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight Unit'])[1]/following::select[1]</value>
      <webElementGuid>59ea0989-06b5-404b-8465-08e784540885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weight'])[1]/following::select[1]</value>
      <webElementGuid>a44eb130-22b9-4a56-9ea6-6372546f8b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Dimension'])[1]/preceding::select[1]</value>
      <webElementGuid>0c860689-e677-4de9-af6a-8df01fc74179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outer Height (mm)'])[1]/preceding::select[1]</value>
      <webElementGuid>357684c6-7883-444a-afb4-46d04fc355ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/div[3]/select</value>
      <webElementGuid>0f5771e8-b9b7-465f-9c88-f3154ee03dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'weight_type' and @name = 'weight_type' and (text() = 'Select Weight TypeGramKG' or . = 'Select Weight TypeGramKG')]</value>
      <webElementGuid>db6f87da-0398-4213-a5cd-3c455bcbaf64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
