<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Electrical Rating220V50Hz220V_8a33e7</name>
   <tag></tag>
   <elementGuidId>c2535140-5b9c-4da4-a56e-8bd246241d71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='electrical_rating']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#electrical_rating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#electrical_rating</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0bf6bc7-03cb-4660-86bf-3e52aeca543d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>electrical_rating</value>
      <webElementGuid>f21b2ec6-d863-4e8c-a290-93c1484ba3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c2e3da2-c543-4107-a32d-ba282aeda28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>electrical_rating</value>
      <webElementGuid>a5ff2b5e-0483-462a-8ff5-265406dd080d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Electrical Rating220V~50Hz220V~60Hz240V~60Hz110V~50Hz110V~60Hz110-240V~50Hz110-240V~60Hz380V~50Hz240V~50HzNon-electric110V~90Hz220V-240V~50/60HzD Battery</value>
      <webElementGuid>b8e27f1e-5c61-4c7e-ab9e-a8f03bf2bfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;electrical_rating&quot;)</value>
      <webElementGuid>76b1d3e1-c20e-4545-943a-46516a66073a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='electrical_rating']</value>
      <webElementGuid>25d63059-a160-4453-aa33-b73180c049e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[2]/div[4]/select</value>
      <webElementGuid>dc894223-fa1c-407b-a522-a8930cffc77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electrical Rating'])[1]/following::select[1]</value>
      <webElementGuid>c6466a15-2f2e-4366-bebd-46912de75434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate'])[1]/following::select[2]</value>
      <webElementGuid>3c291cf9-2506-4466-a91d-a118db056eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assembly'])[1]/preceding::select[1]</value>
      <webElementGuid>b7ca2dc7-8cef-4bb1-9f05-517f6b087998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Original Item (SKU)'])[1]/preceding::select[2]</value>
      <webElementGuid>252777c5-0aec-4d97-825e-c1d416e1c51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>b23e2e83-7809-4ee3-b855-c3a1a7d344a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'electrical_rating' and @name = 'electrical_rating' and (text() = 'Select Electrical Rating220V~50Hz220V~60Hz240V~60Hz110V~50Hz110V~60Hz110-240V~50Hz110-240V~60Hz380V~50Hz240V~50HzNon-electric110V~90Hz220V-240V~50/60HzD Battery' or . = 'Select Electrical Rating220V~50Hz220V~60Hz240V~60Hz110V~50Hz110V~60Hz110-240V~50Hz110-240V~60Hz380V~50Hz240V~50HzNon-electric110V~90Hz220V-240V~50/60HzD Battery')]</value>
      <webElementGuid>8ca8dd26-41bc-4928-8c96-3181a61b9512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
