<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Sub - SubcategoryDowndraft Ho_8564d0</name>
   <tag></tag>
   <elementGuidId>9bcbe9a2-d2a7-490f-b066-06865aae619f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_sub_sub_category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_sub_sub_category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#id_sub_sub_category</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9650937-f885-44e4-9cd6-2e023e86f09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_sub_sub_category</value>
      <webElementGuid>a89f40f6-bcc3-45d1-b835-73c608144c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c14ec028-88ea-4b66-962d-0e6d8240b703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_sub_sub_category</value>
      <webElementGuid>6560cfb8-67d7-45d6-9955-80cbfce011ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Sub - SubcategoryDowndraft HoodBuilt in HoodIsland Lamp HoodIsland Chimney HoodWall Slanted HoodWall Chimney HoodPurifier Slim HoodSlim HoodSlim HoodSlim Hood</value>
      <webElementGuid>b6867740-0596-499b-8ecb-62d674118ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_sub_sub_category&quot;)</value>
      <webElementGuid>ed9dcffe-7346-46e7-bcbf-e423c3bad890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_sub_sub_category']</value>
      <webElementGuid>d83f5c13-b222-4618-bb34-b0d7fde4cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div/div[6]/fieldset/select</value>
      <webElementGuid>1dd6bdc2-5199-4222-b4a5-63782140b681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub - Subcategory'])[1]/following::select[1]</value>
      <webElementGuid>71e7e4d3-814f-44ef-9ed7-7fdc9a936b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcategory'])[1]/following::select[2]</value>
      <webElementGuid>aba60e19-ff99-4ef3-af67-2a053ff146f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Series'])[1]/preceding::select[1]</value>
      <webElementGuid>8b6eca97-c21b-432a-a953-06138e4012b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::select[2]</value>
      <webElementGuid>ff993b43-4041-4caf-933f-cfe4814ae7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/fieldset/select</value>
      <webElementGuid>ca9869db-713e-4a6f-8151-4b16c533cd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id_sub_sub_category' and @name = 'id_sub_sub_category' and (text() = 'Select Sub - SubcategoryDowndraft HoodBuilt in HoodIsland Lamp HoodIsland Chimney HoodWall Slanted HoodWall Chimney HoodPurifier Slim HoodSlim HoodSlim HoodSlim Hood' or . = 'Select Sub - SubcategoryDowndraft HoodBuilt in HoodIsland Lamp HoodIsland Chimney HoodWall Slanted HoodWall Chimney HoodPurifier Slim HoodSlim HoodSlim HoodSlim Hood')]</value>
      <webElementGuid>904b6b7b-c1cf-4830-825e-5b206674ee48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
