<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AX224777RD.JPXDB5J</name>
   <tag></tag>
   <elementGuidId>e205c070-0a92-45a8-a968-54b734b6113b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mTableId_1543757']/div[2]/div/div/table/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;AX224777RD.JPXDB5J&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d29eb821-b7f0-4ac9-a86c-5bed59b9fa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AX224777RD.JPXDB5J</value>
      <webElementGuid>7785ccd2-aa6b-440d-af1c-df1b45e1bba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mTableId_1543757&quot;)/div[2]/div[@class=&quot;row tbl-container&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-12 tbl-fixed&quot;]/table[@class=&quot;table m-table table-condensed&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>aedd4965-2708-4f1e-a681-b1885c5b50c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_1543757']/div[2]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>3b686ac7-e893-486f-8da0-f559bfdd90d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebSync?'])[2]/following::td[3]</value>
      <webElementGuid>33911d94-9d3e-4eeb-ac25-d76eed8296be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sync?'])[2]/following::td[3]</value>
      <webElementGuid>9c1fe359-6b0e-408a-bc55-8f1a629efb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AX 2247 77RD'])[1]/preceding::td[1]</value>
      <webElementGuid>703cd9b2-35c5-450c-9137-e5431abf36c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACURA TLX Type S'])[1]/preceding::td[2]</value>
      <webElementGuid>94839417-9f24-4d00-8240-d66aa5054459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AX224777RD.JPXDB5J']/parent::*</value>
      <webElementGuid>1b6eaaa6-ee97-4c3c-a367-45d526b38ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>3f45163e-c7a4-4c74-97eb-364ecc36f304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AX224777RD.JPXDB5J' or . = 'AX224777RD.JPXDB5J')]</value>
      <webElementGuid>30f12dad-8280-4122-b00c-d444a08fd521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
