<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Show 5Show 10Show 25Show 50Show 100</name>
   <tag></tag>
   <elementGuidId>baed1a5c-524c-4dfa-be7b-3f9d14fc7a39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mTableId_104924']/div[5]/div/div/div/div[3]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2ea8ff33-bcea-4428-aec7-76402027d89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>459879dc-d92d-4eb6-8e32-9a64bc6bd596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show 5Show 10Show 25Show 50Show 100</value>
      <webElementGuid>b636b300-1a57-4421-a60c-04858b1b0ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mTableId_104924&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12&quot;]/div[1]/div[1]/div[3]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>80a67132-37fb-4260-9359-51daef3d26c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_104924']/div[5]/div/div/div/div[3]/select</value>
      <webElementGuid>f9482762-7c96-4ef7-b924-5f7000d338d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GO TO PAGE'])[1]/following::select[2]</value>
      <webElementGuid>c482ca33-3ecb-47a2-beda-ea39b11c1324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[3]/following::select[2]</value>
      <webElementGuid>2782194b-2e8b-4b73-bb48-0586b7a527a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_before'])[1]/preceding::select[1]</value>
      <webElementGuid>4188c1d9-277b-49a6-8057-1dc05f84a38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='navigate_next'])[1]/preceding::select[1]</value>
      <webElementGuid>394bd25c-08af-4249-b14f-aa3294e8b199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>9dbef178-c6e6-4eb6-ab8b-740a1d34e148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Show 5Show 10Show 25Show 50Show 100' or . = 'Show 5Show 10Show 25Show 50Show 100')]</value>
      <webElementGuid>3050953b-053e-4c60-8c9f-62afdcc63caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
