<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_-_m-71</name>
   <tag></tag>
   <elementGuidId>f5fae58c-2746-439b-86b6-796e8b439c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='question-list']/div[2]/div[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.-_m-71</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1.NamaSingle line text.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>358a2191-6c08-414f-9758-56a870b4eb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Single line text</value>
      <webElementGuid>7bc62118-b711-4609-9d7e-9f3dbf32f901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>57470a2f-0ee6-42f4-b3b1-0a3bbd4179c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your answer</value>
      <webElementGuid>210c80f9-89d8-4548-b8c6-e9cd8a72c42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>QuestionId_rf6bbbbfd42944efa8353fe0e66826a4b QuestionInfo_rf6bbbbfd42944efa8353fe0e66826a4b</value>
      <webElementGuid>d69b929f-b907-4e29-b87b-3a6e6fa61952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>-_m-71</value>
      <webElementGuid>58905518-4d4d-40f0-ad67-ffc179be9375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba8533f1-b7de-4d01-87a8-63bf2dd753df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>textInput</value>
      <webElementGuid>d514413b-257d-4ebc-996b-2cb4ecd8654e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;question-list&quot;)/div[@class=&quot;css-55&quot;]/div[@class=&quot;-cj-49&quot;]/div[@class=&quot;-a-65 lrp-text-container&quot;]/span[@class=&quot;-nB-72&quot;]/input[@class=&quot;-_m-71&quot;]</value>
      <webElementGuid>5e4698b4-0ff0-460f-9d00-e0bf6eee016e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='question-list']/div[2]/div[2]/div/span/input</value>
      <webElementGuid>b640b2b7-b26b-4e3f-a4ae-d9298e467209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6c2d65dc-a0df-412f-9f6e-5eadf142901c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your answer']</value>
      <webElementGuid>f0c92696-e3c9-4aad-a58f-8ff7cf1fb761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
