<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Hp_privacy-calculator</name>
   <tag></tag>
   <elementGuidId>3016ea4f-cdbb-4160-a34d-aa06b0191490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='privacy-calculator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#privacy-calculator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#privacy-calculator</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9a94179-ee29-450c-9737-e7ea737751ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cc082568-b043-4b9e-a0fb-6b265a9b5634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calculator-checkbox</value>
      <webElementGuid>434463a5-8617-4423-afb3-b9898f6a8626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>privacy-calculator</value>
      <webElementGuid>1df206ce-00e5-4bfc-80a7-ae6f062fa1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>privacy-calculator</value>
      <webElementGuid>b3fded44-7f40-4ffc-8872-c4587aa4a793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1caf456e-0406-45e3-9a95-a89a26f12d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;privacy-calculator&quot;)</value>
      <webElementGuid>3f421d00-bf1e-4d1c-9048-fe5488e470b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='privacy-calculator']</value>
      <webElementGuid>7690f4ab-7b9b-4fba-ba34-a16f2cde4c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calculator-form']/section[3]/div[2]/div[5]/div/div/input</value>
      <webElementGuid>fa9389a8-7e6e-4ab1-980a-45c202bc327d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>cd235d02-e11b-4357-8c46-28c527b5facc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'privacy-calculator' and @name = 'privacy-calculator']</value>
      <webElementGuid>e35b3700-1161-485d-8451-e56ad7890d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
