<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_t_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>0a3d4e07-0611-4906-8b28-a5c8ad55f11d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='seo_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#seo_description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;t&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d54c5d98-1a0e-4cef-9870-20f2c210c2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>seo_description</value>
      <webElementGuid>1ba4367e-b196-48e6-8197-36823e4509ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>seo_description</value>
      <webElementGuid>2ad4afc4-0570-4434-aa4e-de4d0982e808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dd346b08-f1e8-4717-b958-50c608875c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4d0cb71c-534b-4d97-a93f-253b5fc8add0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>2d98fa9c-5f1a-49d4-aaa4-9487b96d4ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seo_description&quot;)</value>
      <webElementGuid>f51d244f-cc36-4819-ac38-ebc8b9909f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='seo_description']</value>
      <webElementGuid>98f82d6e-59e6-44a0-874b-963ce993a46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div[2]/div/div/form/div/div[3]/div/div[3]/div[2]/div[2]/div/div[2]/div/div/div[2]/textarea</value>
      <webElementGuid>1d26970a-d0a8-4ed1-88be-f3511992ce7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEO Description'])[1]/following::textarea[1]</value>
      <webElementGuid>73f3fe69-1e9d-4975-a272-c1993c3d9a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SEO Title'])[1]/following::textarea[1]</value>
      <webElementGuid>ed591c69-e343-4add-b823-4043e254e0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Display Name'])[1]/preceding::textarea[1]</value>
      <webElementGuid>60ac81a9-0c6b-4d7a-bed2-489cf3609857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='URL AR'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6a2c9434-0ec3-43d1-a22b-437ece5473aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='t']/parent::*</value>
      <webElementGuid>65121386-77a4-48e0-81b1-b06770b60068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/textarea</value>
      <webElementGuid>3f8bb1e1-fc5b-46db-9359-39505aed6343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'seo_description' and @name = 'seo_description' and (text() = 't' or . = 't')]</value>
      <webElementGuid>2b7b6624-970e-4fe9-bffe-da183ceba5b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
