<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__inputenmeta_description</name>
   <tag></tag>
   <elementGuidId>d4aeb0dc-b1fb-4b1c-9e88-a070d6124e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description-chef-en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#description-chef-en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#description-chef-en</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>68ac2d5c-24ac-42ea-8f0a-367ad9f2c798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input[en][meta_description]</value>
      <webElementGuid>a6269519-58db-4897-8514-2cf103372bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description-chef-en</value>
      <webElementGuid>a1685e75-4ebe-4a5d-b534-2837a9452dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>31d8714a-6743-4cc4-a67c-062e9b1b45d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description-chef-en&quot;)</value>
      <webElementGuid>452749d8-4af6-4f7f-a3f8-df8f2103c2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description-chef-en']</value>
      <webElementGuid>247de961-faaa-4f13-a0d2-b29aab073d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-en']/div/div/div[2]/textarea</value>
      <webElementGuid>1bbd1153-7701-4bd8-99e6-b9e205d334ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b0be4a25-5f7b-4c3b-b5ee-f6b1ade4161f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input[en][meta_description]' and @id = 'description-chef-en']</value>
      <webElementGuid>01c43b7a-018a-4cba-b9f3-90d89ebf1008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
