<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__inputidmeta_description</name>
   <tag></tag>
   <elementGuidId>4f2d755c-4abd-4215-832f-92e9811d6ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description-chef-id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#description-chef-id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#description-chef-id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb017c6e-dce1-43ab-aaed-801e6297034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input[id][meta_description]</value>
      <webElementGuid>34a32e6d-fed9-4978-a803-c03922091478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description-chef-id</value>
      <webElementGuid>9d5de01e-16f2-4e27-8dbb-5007466492ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>4ab0d493-b167-4b8d-a75c-3acb987fa968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description-chef-id&quot;)</value>
      <webElementGuid>a9f8497e-e1a0-4a70-8868-d08bc061df51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description-chef-id']</value>
      <webElementGuid>b533e522-a504-4e9d-9841-d07f3247d54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-id']/div/div/div[2]/textarea</value>
      <webElementGuid>7f659276-5170-44e0-b4b6-8851da86ccf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/textarea</value>
      <webElementGuid>2eceeacd-a7e6-4bb1-b570-53345694b840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'input[id][meta_description]' and @id = 'description-chef-id']</value>
      <webElementGuid>4022b4df-4f32-4877-b32a-7c323d208819</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
