<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>abbe98b9-1be7-4c80-bcee-84aeacc35715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-button.p-component.btn.btn-primary.mt-3.btn-regular > span.p-button-label.p-c</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/div[2]/div/div[7]/div/div[2]/div/form/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>30aea76b-f8c6-4121-b421-d7dd67083a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-button-label p-c</value>
      <webElementGuid>9ed80543-aca2-44c4-9cb4-daeec449e8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ae72949f-16e2-4364-bbde-8061d54616ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/main[1]/div[@class=&quot;content-container&quot;]/div[@class=&quot;call-entry-container&quot;]/div[@class=&quot;call-entry-list-product-membership-container&quot;]/div[@class=&quot;custom-tab&quot;]/div[@class=&quot;custom-tab-content tab-content-open&quot;]/div[@class=&quot;mt-3&quot;]/form[1]/button[@class=&quot;p-button p-component btn btn-primary mt-3 btn-regular&quot;]/span[@class=&quot;p-button-label p-c&quot;]</value>
      <webElementGuid>0c811af3-34b0-47e4-8755-e8c2fe651cd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[7]/div/div[2]/div/form/button/span</value>
      <webElementGuid>481fbb87-dc75-44e3-9d09-48aa3386d809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Tracking Note'])[1]/following::span[1]</value>
      <webElementGuid>d1ca8395-2de9-4ae9-9e12-adaca9e5ea4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow Up Action'])[3]/following::span[2]</value>
      <webElementGuid>aa499adb-3aef-4ac6-be29-65cf4d319976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>e9af4493-7471-434e-a01d-175ef9bf2081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>ee132839-93b2-4665-a20c-c74de709bc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
