<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_st</name>
   <tag></tag>
   <elementGuidId>48431319-058c-41d2-94d2-6068b240b1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;vocDescription&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='vocDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>70768f52-8067-4673-9b2f-863e261a077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vocDescription</value>
      <webElementGuid>9a32be44-98d3-4b97-b58f-61495b2d06dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select VOC Description</value>
      <webElementGuid>4993a31b-d2eb-4bee-9eed-e14e53733502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5f52cb16-7265-43bd-8e97-1bd2c351309c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b58af3c7-24ec-49bb-96c7-0c01dee04a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-filled p-inputtextarea-resizable form-textarea</value>
      <webElementGuid>b87306e9-aa9b-4f06-a1b8-302fe04925a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>st</value>
      <webElementGuid>85c422b0-335a-4fc7-b6c6-d8b6e2f0c68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/main[1]/div[@class=&quot;content-container&quot;]/div[@class=&quot;call-entry-container&quot;]/div[@class=&quot;call-entry-list-product-membership-container&quot;]/div[@class=&quot;custom-tab&quot;]/div[@class=&quot;custom-tab-content tab-content-open&quot;]/div[@class=&quot;mt-3&quot;]/form[1]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-3 pr-3&quot;]/div[@class=&quot;form-control&quot;]/div[@class=&quot;input-full-container&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-filled p-inputtextarea-resizable form-textarea&quot;]</value>
      <webElementGuid>17239f23-6519-4eae-9b06-f75b9b0f4407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='vocDescription']</value>
      <webElementGuid>94d79d67-61dc-4153-bcb8-2754a98238d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[7]/div/div[2]/div/form/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>704423c8-fab1-4379-abdc-9456ecbc5032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOC Description'])[1]/following::textarea[1]</value>
      <webElementGuid>6fa36196-6f13-46e8-88ca-ae91e0efda6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Issue'])[2]/following::textarea[1]</value>
      <webElementGuid>9bff61eb-7301-46ed-9c88-028509bdb608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfaction'])[1]/preceding::textarea[1]</value>
      <webElementGuid>7b7ba07e-e82e-4007-966a-1fe2ae175019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfy'])[1]/preceding::textarea[1]</value>
      <webElementGuid>2af51de3-160d-4a52-b28b-58870927b7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>aa478228-ded4-47cd-a15a-845e6acebc73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vocDescription' and @placeholder = 'Select VOC Description' and (text() = 'st' or . = 'st')]</value>
      <webElementGuid>3b33a750-74ee-4df8-b783-673cb057b58c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
