<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_VOC Description_vocDescription</name>
   <tag></tag>
   <elementGuidId>ae9b0fef-676e-4c10-8d22-1d95e829ca7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;vocDescription&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='vocDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8b3781c9-5da0-4e3f-9ab4-b3d13199d4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vocDescription</value>
      <webElementGuid>e022f03d-0c39-4024-9546-0bebcfcc72cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select VOC Description</value>
      <webElementGuid>0e29d667-b84b-4046-9a63-5667be7ee08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>84ba6698-b665-431c-beab-90fcf247e79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>298d48be-b72e-4b7e-a3da-4f00742a0941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtextarea p-inputtext p-component p-inputtextarea-resizable form-textarea p-filled</value>
      <webElementGuid>038b6466-7cf5-4b2f-8641-cb2acfc897c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/main[1]/div[@class=&quot;content-container&quot;]/div[@class=&quot;call-entry-container&quot;]/div[@class=&quot;call-entry-list-product-membership-container&quot;]/div[@class=&quot;custom-tab&quot;]/div[@class=&quot;custom-tab-content tab-content-open&quot;]/div[@class=&quot;mt-3&quot;]/form[1]/div[@class=&quot;grid&quot;]/div[@class=&quot;col-3 pr-3&quot;]/div[@class=&quot;form-control&quot;]/div[@class=&quot;input-full-container&quot;]/textarea[@class=&quot;p-inputtextarea p-inputtext p-component p-inputtextarea-resizable form-textarea p-filled&quot;]</value>
      <webElementGuid>d9ca8f58-6210-41dc-a984-f3669e19361d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='vocDescription']</value>
      <webElementGuid>a4f7c36f-67eb-4d6c-a8e4-50cfa5538823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div[2]/div/div[7]/div/div[2]/div/form/div[2]/div/div[2]/div/textarea</value>
      <webElementGuid>0934b2aa-2b56-4696-a444-6ad9da2067ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOC Description'])[1]/following::textarea[1]</value>
      <webElementGuid>5eb8cdd6-c1d0-4b7c-a967-6c2001a7cee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Issue'])[2]/following::textarea[1]</value>
      <webElementGuid>920719f2-d6f2-4a4c-b099-18bac1dda25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfaction'])[1]/preceding::textarea[1]</value>
      <webElementGuid>530b6387-6a44-499f-9f12-7dfd3ec609d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Satisfy'])[1]/preceding::textarea[1]</value>
      <webElementGuid>278a7b94-d04f-489d-a7c2-6794d005343b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>bccdd944-ac5d-475f-a6c6-374186f60f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vocDescription' and @placeholder = 'Select VOC Description']</value>
      <webElementGuid>33b52272-cd4c-4ec9-945b-c7e4c20f6c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
