<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Hp_telp</name>
   <tag></tag>
   <elementGuidId>1bb711a4-ecca-450a-9617-9efde6a84a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='telp'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.text-left > #telp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;No Hp&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9a16fa1-6b2d-4a98-b99f-e6becbc846e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a2b7d60-3f29-4cd0-b8fe-1811a8ddcc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Hp</value>
      <webElementGuid>6f2145a6-0001-4bbc-8984-91f98cfbac71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-calculator telp</value>
      <webElementGuid>bf640720-291a-408a-a609-69b8d2c31eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telp</value>
      <webElementGuid>79a8de4b-66a0-4aae-8420-f00ab47f3c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telp</value>
      <webElementGuid>a1281202-f042-42f3-bc42-f0c319879d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>bc2be18e-ef70-4ce5-832a-8374bce808da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculator-form&quot;)/section[@class=&quot;section-3 active-section&quot;]/div[@class=&quot;wrap-form-calculator&quot;]/div[@class=&quot;row d-flex justify-content-center mt-5&quot;]/div[@class=&quot;col-md-6 text-left&quot;]/input[@id=&quot;telp&quot;]</value>
      <webElementGuid>292ecbfd-b177-41d1-8e05-b04a78adf648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='telp'])[2]</value>
      <webElementGuid>93ad9c11-7ab5-411d-a12c-661b5f2b6c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calculator-form']/section[3]/div[2]/div[4]/div/input</value>
      <webElementGuid>379ec2d7-5fb9-469c-b11c-3df3e5f662c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>ed01ed2a-c74f-471c-8f8c-fd8ed89cd2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'No Hp' and @id = 'telp' and @name = 'telp']</value>
      <webElementGuid>1b1f426d-f1e1-4187-ae1e-20f3f09219d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
