<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select BrandHONDATOYOTAENERGYMODENA _21fc10</name>
   <tag></tag>
   <elementGuidId>ac9e82b6-e1c7-48ee-ac00-ffee6f3a100b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='id_brand']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#id_brand</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3d0e291d-d374-49ae-92e3-617c335ee8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_brand</value>
      <webElementGuid>b91fa2d6-731e-4f55-b9e4-97084b724426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>28fde066-6d6c-4783-bc46-529b9cdf2c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_brand</value>
      <webElementGuid>372b7fb0-2e31-453d-a90f-b69128cc60e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select BrandHONDATOYOTAENERGYMODENA ProfessionalDOMOMODENA</value>
      <webElementGuid>ca075be7-9910-40e6-9645-d5031c95fa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_brand&quot;)</value>
      <webElementGuid>c9982f35-2106-4edb-9509-4409504dbec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='id_brand']</value>
      <webElementGuid>3761a65b-8966-4e8b-a47b-c75ade347b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div/div[2]/select</value>
      <webElementGuid>146c85d1-d921-4b84-a8f6-e88ec44dfd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brand'])[2]/following::select[1]</value>
      <webElementGuid>e6423ce0-eda2-4a96-b4de-9113cec2f411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcategory Prefix'])[1]/following::select[2]</value>
      <webElementGuid>e8e0cb62-7d95-4abc-8616-b483118279b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Segment'])[1]/preceding::select[1]</value>
      <webElementGuid>4c4276d8-fd25-4b6b-9344-58ef4b248484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/preceding::select[2]</value>
      <webElementGuid>56193020-a9f0-48aa-b2b7-99b9b3f267ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7240df92-da7e-4d9f-ac9c-a046b4cc1f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'id_brand' and @name = 'id_brand' and (text() = 'Select BrandHONDATOYOTAENERGYMODENA ProfessionalDOMOMODENA' or . = 'Select BrandHONDATOYOTAENERGYMODENA ProfessionalDOMOMODENA')]</value>
      <webElementGuid>d86646ec-fedb-4913-b444-ff353cd3e46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
