<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select ColorBlackBlack GlassBlack Ma_44b2d0</name>
   <tag></tag>
   <elementGuidId>0fede7b8-937c-451b-bda8-8d46ebf55214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='color']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#color</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#color</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9cbf6cb6-db3e-4401-b0f2-22181d01f636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>d9fa068e-ee74-497d-83db-5bea0ebc3401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ce3784d-af20-48e7-8409-65f3081484f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>6f342f9c-79a1-497e-90d0-8b30cdc5e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ColorBlackBlack GlassBlack MagmaBlack StainlessBlueBrownChromeDark GreyDark SteelElementoGlass BlackGlass WhiteGoldGold BlackGreenGreen Young GreyGun MetalINOXMatte BlackMercury GreyOrangePinkPINKcorRedSatinSatin StainlessSilverStainlesstestqTitanium SIlverTricoloreTurquoiseVioletWhiteWhite PolarisYellow</value>
      <webElementGuid>bd5494c7-3569-4209-a497-6ded6a2b4aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color&quot;)</value>
      <webElementGuid>47eff541-c8b4-4320-a13f-8ac10d11f2bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='color']</value>
      <webElementGuid>3f209ad1-dcc4-413f-bcd0-21b44b9c2e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/form/div[2]/div[3]/div[2]/div/select</value>
      <webElementGuid>56deb0ae-c484-4d45-8f2a-3ae09b6475fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>80abb0f5-fad5-40e9-9096-4534b70d0006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publish Web'])[1]/following::select[1]</value>
      <webElementGuid>906d43f8-09c9-4f88-8b03-386d9cd5b2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::select[1]</value>
      <webElementGuid>8109990d-e7e7-425c-a6bf-fc3e7cc24028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate'])[1]/preceding::select[2]</value>
      <webElementGuid>77b65176-908e-42b8-91f2-74746d2d40b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/select</value>
      <webElementGuid>47a845aa-3f67-472a-8038-fc721ac8f9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'color' and @name = 'color' and (text() = 'Select ColorBlackBlack GlassBlack MagmaBlack StainlessBlueBrownChromeDark GreyDark SteelElementoGlass BlackGlass WhiteGoldGold BlackGreenGreen Young GreyGun MetalINOXMatte BlackMercury GreyOrangePinkPINKcorRedSatinSatin StainlessSilverStainlesstestqTitanium SIlverTricoloreTurquoiseVioletWhiteWhite PolarisYellow' or . = 'Select ColorBlackBlack GlassBlack MagmaBlack StainlessBlueBrownChromeDark GreyDark SteelElementoGlass BlackGlass WhiteGoldGold BlackGreenGreen Young GreyGun MetalINOXMatte BlackMercury GreyOrangePinkPINKcorRedSatinSatin StainlessSilverStainlesstestqTitanium SIlverTricoloreTurquoiseVioletWhiteWhite PolarisYellow')]</value>
      <webElementGuid>e959b5f6-b920-4744-9268-e410655792a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
