<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Korporasi_fi-rr-shopping-cart</name>
   <tag></tag>
   <elementGuidId>84df3d59-802f-4b6c-b4a3-e8c337a8c411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fi-rr-shopping-cart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div[2]/div/div[3]/ul/li[2]/div/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0e7e57d2-13bf-4e61-963b-a0d3bfb6790b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-rr-shopping-cart</value>
      <webElementGuid>b6a52f58-80de-4871-aa54-2682420aa4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;header-nav shadow-sm navbar navbar-expand-lg navbar-light&quot;]/div[@class=&quot;container-xl header-nav--inner position-relative&quot;]/div[@class=&quot;header-nav--menu-info header-nav--menu-info-responsive&quot;]/ul[1]/li[2]/div[@class=&quot;dropdown cart-dropdown&quot;]/a[@class=&quot;header-link&quot;]/i[@class=&quot;fi-rr-shopping-cart&quot;]</value>
      <webElementGuid>6e7230a7-40ad-43b5-bd66-9b6b1a65c4ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div[2]/div/div[3]/ul/li[2]/div/a/i</value>
      <webElementGuid>207fd4e8-3d9a-4c1e-96e2-64b4efbfc7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a/i</value>
      <webElementGuid>6ca6ceca-6154-43b7-8e2a-addd29797fff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
