<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KotaBarito SelatanBarito Timur_800a3c</name>
   <tag></tag>
   <elementGuidId>f35477b9-c8b5-40f6-a86b-a65f301aef3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#city</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aff68be1-3a3e-489a-ae14-5b995e2f483c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select form-control w-100</value>
      <webElementGuid>f5a47f56-6974-4a48-bcd0-eae24a4b43a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>66366ab8-e5f7-44a8-8d77-d2018ffa8f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city_id</value>
      <webElementGuid>ca5581e9-387d-4fa8-80bc-dcdead06e401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KotaBarito SelatanBarito TimurBarito UtaraGunung MasKapuasKatinganLamandauMurung RayaPalangka RayaPulang PisauSeruyanSukamarawaringin Baratwaringin Timur</value>
      <webElementGuid>7c9009d8-2844-4af7-b7c2-4972998426a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city&quot;)</value>
      <webElementGuid>b694b712-8b3c-42d0-8634-3f60ceae9534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='city']</value>
      <webElementGuid>bc9bfb95-b699-4fb8-a320-f49b2928c709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-address-add']/div/div[9]/select</value>
      <webElementGuid>ec35c9b8-7e71-49c7-b630-c525e96fc5fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/following::select[1]</value>
      <webElementGuid>5cb0d5a3-13d1-4c5e-abb7-8eac4ce893f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi'])[1]/following::select[2]</value>
      <webElementGuid>1b7c10bb-912c-44b8-b47a-fdfc33113ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[1]/preceding::select[1]</value>
      <webElementGuid>c56c55d7-0056-459c-8a99-c6e0b5268f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/preceding::select[2]</value>
      <webElementGuid>a86c5d23-ebfa-4134-b46e-93d4a94425a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>50b28be3-156e-4aac-9a00-78fdbf4e2d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'city' and @name = 'city_id' and (text() = 'Pilih KotaBarito SelatanBarito TimurBarito UtaraGunung MasKapuasKatinganLamandauMurung RayaPalangka RayaPulang PisauSeruyanSukamarawaringin Baratwaringin Timur' or . = 'Pilih KotaBarito SelatanBarito TimurBarito UtaraGunung MasKapuasKatinganLamandauMurung RayaPalangka RayaPulang PisauSeruyanSukamarawaringin Baratwaringin Timur')]</value>
      <webElementGuid>04e4aebd-2aef-4b75-88f7-74bc8dbaf964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
