<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Performance</name>
   <tag></tag>
   <elementGuidId>75254b3f-fbbd-4a3d-95d4-fa2870b698be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[8]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Performance&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ead9c3c-d9f4-440e-9efc-53ae595a91a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer</value>
      <webElementGuid>0d527cff-1232-4883-9802-b89bb9eb9cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Performance</value>
      <webElementGuid>8fbae464-dfcc-4bf7-8453-9eacd3d46f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;false&quot;]/div[@class=&quot;px-8 pb-2 w-full&quot;]/div[@class=&quot;flex h-12 justify-between&quot;]/div[@class=&quot;flex xl:gap-6 sm:gap-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative group pr-6 pt-5&quot;]/div[@class=&quot;xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer&quot;]</value>
      <webElementGuid>350aebbb-4930-49fa-9756-d163141ee704</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[8]/div[2]/div</value>
      <webElementGuid>b33599e5-889c-4668-81cd-e01a0cc1e932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resign Approval'])[1]/following::div[4]</value>
      <webElementGuid>296dd68f-f02d-4dc2-9b65-96191fd9bc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Resign'])[1]/following::div[5]</value>
      <webElementGuid>ea2e9c90-d8e1-4542-b772-35f4053329d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization Performance Plan Approval'])[1]/preceding::div[2]</value>
      <webElementGuid>f68d0317-907f-48c2-8e1c-3be5a40bde6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Performance']/parent::*</value>
      <webElementGuid>d57ce882-7fb5-472d-b620-d43a0f9f679b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div</value>
      <webElementGuid>fe41be9e-dc59-4b42-9d4b-4f768f54502a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Performance' or . = 'Performance')]</value>
      <webElementGuid>e7a55123-3df8-4f9c-9936-1381a2ef007c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
