<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih KecamatanBalikpapan BaratBalik_a2d421</name>
   <tag></tag>
   <elementGuidId>742ba018-1fc6-4171-b314-cbff97ed930b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='kecamatan_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kecamatan_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#kecamatan_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d9f6c8c-4bd0-41f4-aba7-2e0d36352db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select form-control</value>
      <webElementGuid>6b73ddd8-cee3-44ce-bdfe-9c326a64be23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kecamatan_id</value>
      <webElementGuid>82c5903a-b90e-4c14-a7bc-f87e151e7079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_district</value>
      <webElementGuid>2ea693fc-2940-4ac4-93be-4bf5c69e29d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih KecamatanBalikpapan BaratBalikpapan KotaBalikpapan SelatanBalikpapan TengahBalikpapan TimurBalikpapan Utara</value>
      <webElementGuid>450fe4bc-2833-4762-8c4a-d8a9be77c7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kecamatan_id&quot;)</value>
      <webElementGuid>3cb7cf6d-6f0f-455c-bbee-c7404e122b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kecamatan_id']</value>
      <webElementGuid>6e2b65a4-9345-43f1-96fb-62ed11b67e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='rental_form']/div/div/div[8]/div/select</value>
      <webElementGuid>4c41268b-c151-4aea-aaa9-6829b641fb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>e5329c26-7e4e-4470-bb57-c8551c4f776e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>9bf2feb4-a2de-47af-9a68-dcc7fe569469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>e2ba2506-3bf1-416d-8c04-b25471a2904c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'kecamatan_id' and @name = 'id_district' and (text() = 'Pilih KecamatanBalikpapan BaratBalikpapan KotaBalikpapan SelatanBalikpapan TengahBalikpapan TimurBalikpapan Utara' or . = 'Pilih KecamatanBalikpapan BaratBalikpapan KotaBalikpapan SelatanBalikpapan TengahBalikpapan TimurBalikpapan Utara')]</value>
      <webElementGuid>0ec1a358-7944-4c08-8b48-eff2bcbf6c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
