<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_preddy.desmonmodena.com</name>
   <tag></tag>
   <elementGuidId>e5a5760a-5537-4067-9e8c-81bc2155b214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/section/div/div/div/div/div[2]/form/div[3]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ml-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78a1cf90-a915-4de6-b3d0-5876a95d1c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2</value>
      <webElementGuid>9246f0e6-80d0-4888-8dd0-5b77312bb552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>preddy.desmon@modena.com</value>
      <webElementGuid>2581299e-988e-4825-88bd-a335847233be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;mt-1 p-2&quot;]/div[@class=&quot;d-flex align-items-center w-100 p-1 mb-1&quot;]/span[@class=&quot;ml-2&quot;]</value>
      <webElementGuid>3db0fb70-7dc2-43fb-87ad-5cf21425e847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/section/div/div/div/div/div[2]/form/div[3]/div/div/div/div/span</value>
      <webElementGuid>18955250-a60d-45d6-b44f-e42bfaf720e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[1]</value>
      <webElementGuid>48b7bf7d-9a41-4826-bb6d-697b950614f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Image'])[1]/following::span[1]</value>
      <webElementGuid>a4f07e1e-c6c5-429b-809c-547c6a7d8b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='preddy.desmon@modena.com'])[2]/preceding::span[1]</value>
      <webElementGuid>9bfed72f-7564-4a5f-9c39-ee692ead90a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::span[2]</value>
      <webElementGuid>67d78622-b49d-48e4-a38e-5533003c53d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span</value>
      <webElementGuid>ad031437-5a37-4e42-99da-1ffe196b9f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'preddy.desmon@modena.com' or . = 'preddy.desmon@modena.com')]</value>
      <webElementGuid>938c9a86-e43e-4491-a156-19bb92b0aabc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
