<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customer_name</name>
   <tag></tag>
   <elementGuidId>a8590773-c6f0-4e02-9a22-d77f23fd016a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customer_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customer_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3b4e238-9c07-4983-bc85-54f830a1b8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca0ea317-8685-4882-833e-9c0ddd4a16a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_name</value>
      <webElementGuid>9a1618f7-9547-4095-a6c4-440c9beecb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs </value>
      <webElementGuid>26662476-f7ca-4ffd-8326-b03b25c94cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Customer</value>
      <webElementGuid>23249a9b-d226-402d-9ac3-7f3a8bd03b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;body full&quot;]/div[@class=&quot;wrapper_all&quot;]/div[@class=&quot;wrapper_content&quot;]/div[2]/div[@class=&quot;detail_wrap_main__jAM1f&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-7 col-12&quot;]/div[@class=&quot;detail_wrap_form2__4g2Yy&quot;]/div[@class=&quot;detail_wrapper_form__YTXW1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;detail_input_search_menu__nE5OT cursor-pointer text-base max-[430px]:text-xs&quot;]</value>
      <webElementGuid>0af5ac4b-45fa-4f72-9a10-3e97d3090017</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customer_name']</value>
      <webElementGuid>a2fcd1b4-cd0c-4bb5-a544-8884accdc047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/form/div/div/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>c4d8f06e-b970-4c92-a989-4a1f5a160e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0b814dce-bc29-41a5-8352-6573fbf03f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customer_name' and @placeholder = 'Select Customer']</value>
      <webElementGuid>cda26a5d-177e-4234-8625-e888aecf0b87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
