<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master</name>
   <tag></tag>
   <elementGuidId>6a7752e4-016f-4ff3-967b-69d9d35fa82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[10]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Master&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0339660b-2cda-4c25-89b7-b6d6342e3360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer</value>
      <webElementGuid>a4f1df9e-eca3-4429-a38d-d096abd3b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Master</value>
      <webElementGuid>762acb75-3b79-43ef-8ee3-ed6fd98901a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;false&quot;]/div[@class=&quot;px-8 pb-2 w-full&quot;]/div[@class=&quot;flex h-12 justify-between&quot;]/div[@class=&quot;flex xl:gap-6 sm:gap-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;relative group pr-6 pt-5&quot;]/div[@class=&quot;xl:text-sm text-xs font-medium text-white hover:text-emerald-500 pt-1 cursor-pointer&quot;]</value>
      <webElementGuid>f621e322-88c1-4542-a84d-32e941ca8073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div/div/div/div/div/div[10]/div/div</value>
      <webElementGuid>da20e2ca-d4a8-4b50-9907-48781aa28fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resign Report'])[1]/following::div[3]</value>
      <webElementGuid>ba37eb77-c05b-4da7-810d-0af1aad1f8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PMK Report'])[1]/following::div[4]</value>
      <webElementGuid>a8c03d10-1777-4bdb-8964-4728c18f4614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MPP Period Setting'])[1]/preceding::div[2]</value>
      <webElementGuid>4e2c29ec-8637-4a5c-81fd-cb04a620588f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alternate Approval Setting'])[1]/preceding::div[3]</value>
      <webElementGuid>5c018902-da0d-4a0b-9839-0ea8c3b1a6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master']/parent::*</value>
      <webElementGuid>9c88a35b-98ab-470e-8bb0-2637f8fd7831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div</value>
      <webElementGuid>fc4fb06f-3541-41db-a758-22115f60f2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Master' or . = 'Master')]</value>
      <webElementGuid>53585e1e-a562-4b92-94a0-531dcb6a4a31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
