<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization Performance Plan_perform_8e163e</name>
   <tag></tag>
   <elementGuidId>6c0c671f-5d5d-4e33-b05c-9e58ac14a6a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;performance_num&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='performance_num']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Performance Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1eb1b774-08dd-4105-b444-21468f33bdbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a304ecc9-41c1-4b1b-a2df-40bd1b1781a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>performance_num</value>
      <webElementGuid>49bd2bb9-f5a2-40ba-baed-82abbf8e056c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8a83cf1e-7193-4d73-a048-ba7c6b22b4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full rounded-lg border-0 px-2 bg-neutral-800 text-white py-2 placeholder:text-white placeholder:font-thin placeholder:text-sm</value>
      <webElementGuid>35ad8ebf-0a9d-44ee-bc5c-99524d54a029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Performance Number</value>
      <webElementGuid>8cdcd9a8-0848-4150-8736-992c9f40583c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-12&quot;]/nav[@class=&quot;w-full pb-6&quot;]/div[@class=&quot;mx-auto pt-4 px-8 grid grid-cols-5 gap-x-4 gap-y-2&quot;]/div[@class=&quot;mt-2&quot;]/input[@class=&quot;block w-full rounded-lg border-0 px-2 bg-neutral-800 text-white py-2 placeholder:text-white placeholder:font-thin placeholder:text-sm&quot;]</value>
      <webElementGuid>4ea3e8d8-f237-491c-87ae-ad270986d695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='performance_num']</value>
      <webElementGuid>0525c85e-0b6c-4c2b-9cf4-08981e09ce89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/nav/div[3]/div/input</value>
      <webElementGuid>d89ea25c-a034-421d-b482-0ed442672392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>deb8be16-0b3e-4104-91c2-94365e778cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'performance_num' and @placeholder = 'Performance Number']</value>
      <webElementGuid>2bb0c451-81b7-4db2-8e26-d40b830ec062</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
