<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Job Category</name>
   <tag></tag>
   <elementGuidId>03b5f5d9-5135-435d-985a-b1b730f8faca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/ul/li[7]/ul/a[5]/li/ul/a/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.sub-sub-menu-list</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca43a096-3477-4b49-9c6a-e83c0a09553f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-sub-menu-list</value>
      <webElementGuid>8109f2f2-9568-44c5-9e1e-e0a8e43b89c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Category</value>
      <webElementGuid>25b45da2-3a71-4983-97ba-61b0ec31fd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;layout&quot;]/nav[@class=&quot;sidebar&quot;]/ul[1]/li[@class=&quot;menu-container sidebar-show&quot;]/ul[@class=&quot;sub-menu&quot;]/a[5]/li[@class=&quot;sub-menu-list&quot;]/ul[@class=&quot;sub-sub-menu&quot;]/a[1]/li[@class=&quot;sub-sub-menu-list&quot;]</value>
      <webElementGuid>b8b96da4-b39d-4afc-871b-5281c5e2a5bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/ul/li[7]/ul/a[5]/li/ul/a/li</value>
      <webElementGuid>7e882522-1abc-49d1-b96a-732b178876de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Knowledge'])[1]/following::li[1]</value>
      <webElementGuid>3cd1a520-2e44-49f3-9a5f-1fba546f40d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOC'])[1]/following::li[2]</value>
      <webElementGuid>74514ec0-c1f2-40a9-8a10-ff7ece7e69dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Area'])[1]/preceding::li[1]</value>
      <webElementGuid>10ad6330-dfb1-4dc9-9c2f-e6662b34aee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge'])[1]/preceding::li[2]</value>
      <webElementGuid>99883db5-af91-48cd-8516-4b7feafe897a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/li/ul/a/li</value>
      <webElementGuid>68f29f81-473f-4436-bec6-756ac76202e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Job Category' or . = 'Job Category')]</value>
      <webElementGuid>61d49929-0b0d-472f-9d70-2ab2793a1909</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
