<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Secondary Data Skow</name>
   <tag></tag>
   <elementGuidId>8fe61e75-ac7f-4a67-9209-b43829be704f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='tabs_history']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabs_history > li:nth-of-type(2) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Secondary Data Skow&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3e1cb1a-0813-41b7-91d4-de6838cde4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#secondary-data</value>
      <webElementGuid>0b5f5807-97ea-45e3-8ca6-01f95ba988f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>92dddcb6-3969-438a-9ee4-71b8a787adb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secondary Data Skow</value>
      <webElementGuid>c2e7df22-942a-4a67-a5fd-87576c039b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs_history&quot;)/li[2]/a[1]</value>
      <webElementGuid>4a203923-afb5-4a99-a61b-aa0faf13cd00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabs_history']/li[2]/a</value>
      <webElementGuid>3e7c34b8-a707-4b93-a4e1-505ab975b477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Secondary Data Skow')]</value>
      <webElementGuid>1158a6df-d949-408d-bc8c-8f9320d5275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Data'])[1]/following::a[1]</value>
      <webElementGuid>25952b2f-1a10-4f9c-96e4-6010ee78500b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part'])[2]/following::a[2]</value>
      <webElementGuid>598b7616-b0c0-4a9c-a04a-a89da31c69da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Substitution'])[1]/preceding::a[1]</value>
      <webElementGuid>1f4ae64c-d7e4-4e23-8e25-5e2bda780fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Files'])[1]/preceding::a[2]</value>
      <webElementGuid>a4102e26-84a8-406c-9e5e-b71a0c4f19eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Secondary Data Skow']/parent::*</value>
      <webElementGuid>105455de-fbdf-4fef-9bbd-71deab550251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#secondary-data')]</value>
      <webElementGuid>5eb6e2b6-12d9-4899-82fd-ff2d2d6ee378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ul/li[2]/a</value>
      <webElementGuid>993ccae1-0f86-47d9-a537-81c9914fcc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#secondary-data' and (text() = 'Secondary Data Skow' or . = 'Secondary Data Skow')]</value>
      <webElementGuid>1f8ffe1a-0412-4320-a799-92dfc018ae7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
