<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>785b7322-75ba-4f82-8ca6-469f3f4a0601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='caret-down']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ROSDINI&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7772db32-41b1-4bbb-afc4-72689ed7276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://gccs-test.modena.com/media/user/default.png</value>
      <webElementGuid>31e47206-4a5c-4905-af5c-3601ebc35451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ROSDINI</value>
      <webElementGuid>342215f1-00da-404b-a6b6-ecfb7f226953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;caret-down&quot;)/img[1]</value>
      <webElementGuid>0e98096c-f72b-4a44-9755-4d8a9c2ac7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='caret-down']/img</value>
      <webElementGuid>f6f5d1fa-e9ce-40ff-b632-b5102fb1221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROSDINI'])[1]/preceding::img[1]</value>
      <webElementGuid>6e3d79ca-18fd-4dc2-a268-807203664e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::img[2]</value>
      <webElementGuid>7f5f1808-e919-4a27-b013-0a857be56106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ROSDINI']</value>
      <webElementGuid>8a1ff68d-ee76-4bba-9ca0-425e12921501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>371073da-fdbc-48a2-8179-287c5807262c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://gccs-test.modena.com/media/user/default.png' and @alt = 'ROSDINI']</value>
      <webElementGuid>6641d678-b023-46c7-8908-34bed5e7b4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
