<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Call_p-ink</name>
   <tag></tag>
   <elementGuidId>ae2bdd62-e592-4027-a5f7-f027deb23bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr_id_15_content']/div[2]/div/div[2]/button[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c168ffb-cdb2-40e6-9cf4-555538ff014c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6c00b9bd-5a30-44bf-a11f-6e595f12ac81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ink</value>
      <webElementGuid>ad06966b-4ec3-4415-ab5b-b4bd0fb71e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_15_content&quot;)/div[@class=&quot;flex-1&quot;]/div[@class=&quot;align-items-center&quot;]/div[@class=&quot;flex my-5&quot;]/button[@class=&quot;p-button p-component btn btn-success mx-2 btn-regular&quot;]/span[@class=&quot;p-ink&quot;]</value>
      <webElementGuid>9abb8015-8ea2-4084-909d-510330c59bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr_id_15_content']/div[2]/div/div[2]/button[2]/span[2]</value>
      <webElementGuid>2723ce55-163c-4a78-9d67-5e0092cc961f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/span[2]</value>
      <webElementGuid>58ea05ba-5094-423b-8732-eda05c9c7183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
