<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_customerInfoRemarks</name>
   <tag></tag>
   <elementGuidId>7118fe75-6545-4d6e-a06b-374aedd17d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ciao-wa-modal_content > div:nth-of-type(2) > div.mx-2.my-5.align-items-center > div.flex > textarea[name=&quot;customerInfoRemarks&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@name='customerInfoRemarks'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6d709dc1-0e2a-4b6e-8877-f8c88d5097ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerInfoRemarks</value>
      <webElementGuid>23808d03-a7de-421f-9b71-b95cd37ce52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputtextarea flex-1 mr-3</value>
      <webElementGuid>d07c95bf-5d17-4301-8c7a-0ae2028c8150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe661ff1-2796-4199-9a2d-8aebf6160043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>07f076d5-b196-4e55-89a1-62f989e19069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ciao-wa-modal_content&quot;)/div[2]/div[@class=&quot;mx-2 my-5  align-items-center&quot;]/div[@class=&quot;flex&quot;]/textarea[@class=&quot;p-inputtext p-component p-inputtextarea flex-1 mr-3&quot;]</value>
      <webElementGuid>5cccbaec-ccc9-49de-ab6c-b57e5b8c524a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@name='customerInfoRemarks'])[3]</value>
      <webElementGuid>5d9dca9d-672a-464b-b2d1-33b0094e8edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ciao-wa-modal_content']/div[2]/div/div[2]/textarea</value>
      <webElementGuid>c64d4ad1-ad9d-457f-9e00-586a481b6ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div[2]/textarea</value>
      <webElementGuid>6a85c3b4-0d63-4f34-8bc0-a54cf5bd49bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'customerInfoRemarks' and @type = 'text']</value>
      <webElementGuid>875b61d0-6f07-4f26-97fd-c4bfbddff5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
