<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AX923566GB.BSBXC4H</name>
   <tag></tag>
   <elementGuidId>a3a85cb9-890b-46ac-a2c9-524db1be8466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/section/div/div/div/div/div/div[3]/div/div[2]/div[1]/div/table/tbody/tr[1]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'AX923566GB.BSBXC4H' or . = 'AX923566GB.BSBXC4H')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;AX923566GB.BSBXC4H&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6bfca57f-618b-4dce-9713-01e7017e663b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AX923566GB.BSBXC4H</value>
      <webElementGuid>5cdecd07-7cda-4d3e-8500-e42bf6d1af6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mTableId_5072819&quot;)/div[2]/div[@class=&quot;row tbl-container&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-12 tbl-fixed&quot;]/table[@class=&quot;table m-table table-condensed&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>576beef9-0059-4466-b55e-461bad5cbe86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_5072819']/div[2]/div/div/table/tbody/tr/td[3]</value>
      <webElementGuid>42dd02a9-bebb-44c8-94e8-5eb616de704e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebSync?'])[2]/following::td[3]</value>
      <webElementGuid>4a144c9a-d9fe-4230-9a21-dc81c24df60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sync?'])[2]/following::td[3]</value>
      <webElementGuid>db8d41f6-7601-4ff0-9e56-c2ec3687a45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AX 9235 66GB'])[1]/preceding::td[1]</value>
      <webElementGuid>cc872bc1-b473-44f0-bad7-7335789e3bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/preceding::td[2]</value>
      <webElementGuid>a56dc7dc-b1b7-4759-8d5c-3aa102f1686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AX923566GB.BSBXC4H']/parent::*</value>
      <webElementGuid>50a0a45c-ca27-4bfb-a161-2ac742aa79f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>6b77f4dc-7b54-4c04-81e0-cd65cd2acd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AX923566GB.BSBXC4H' or . = 'AX923566GB.BSBXC4H')]</value>
      <webElementGuid>e266a902-efff-4ec5-9dbe-f8383ec2945a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mTableId_5893862']/div[2]/div/div/table/tbody/tr[3]/td[3]</value>
      <webElementGuid>192aa214-954f-4c0a-9db2-8b8238a13ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hood'])[2]/following::td[6]</value>
      <webElementGuid>c3fcd9f4-e640-4f5b-b043-1b6bf6d3fed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cooking'])[2]/following::td[7]</value>
      <webElementGuid>a7479756-ee91-4c60-b094-c7513a8da094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[3]/preceding::td[2]</value>
      <webElementGuid>d837457d-6658-4402-a5b6-3bdaee7551f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]</value>
      <webElementGuid>1935ccf2-4256-4735-8c41-240a67aff426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
